// German irregular verbs — present tense (Präsens)
// Each conjugation: prefix (static before), target (what user types), suffix (static after)
// irregular: true on forms where the stem vowel mutates

const c = (pronoun, full, prefix, target, suffix, irregular = false) =>
  ({ pronoun, full, prefix, target, suffix, irregular });

export const IRREGULAR_VERBS = [
  {
    id: 1,
    infinitive: "sein",
    en: "to be",
    es: "ser / estar",
    pattern: { en: "Fully irregular", es: "Completamente irregular" },
    note: {
      en: "The most important verb in German — completely irregular. Every form must be memorized individually.",
      es: "El verbo más importante del alemán — completamente irregular. Cada forma debe memorizarse individualmente.",
    },
    conjugations: [
      c("ich",       "bin",   "",      "bin",   "", true),
      c("du",        "bist",  "",      "bist",  "", true),
      c("er/sie/es", "ist",   "",      "ist",   "", true),
      c("wir",       "sind",  "",      "sind",  "", true),
      c("ihr",       "seid",  "",      "seid",  "", true),
      c("sie/Sie",   "sind",  "",      "sind",  "", true),
    ],
  },
  {
    id: 2,
    infinitive: "haben",
    en: "to have",
    es: "tener",
    pattern: { en: "Partially irregular (du/er drop the -b-)", es: "Parcialmente irregular (du/er pierden la -b-)" },
    note: {
      en: "Du and er/sie/es lose the -b- from the stem: haben → hast, hat. Very common auxiliary verb.",
      es: "Du y er/sie/es pierden la -b- del stem: haben → hast, hat. Auxiliar muy común.",
    },
    conjugations: [
      c("ich",       "habe",  "hab",  "e",    ""),
      c("du",        "hast",  "h",    "ast",  "", true),
      c("er/sie/es", "hat",   "h",    "at",   "", true),
      c("wir",       "haben", "hab",  "en",   ""),
      c("ihr",       "habt",  "hab",  "t",    ""),
      c("sie/Sie",   "haben", "hab",  "en",   ""),
    ],
  },
  {
    id: 3,
    infinitive: "werden",
    en: "to become / will (future)",
    es: "convertirse / (futuro)",
    pattern: { en: "Partially irregular (du/er vowel shift)", es: "Parcialmente irregular (cambio vocálico en du/er)" },
    note: {
      en: "Used to form the future tense. Du wirst and er wird have an unexpected e→i vowel shift.",
      es: "Se usa para el futuro. Du wirst y er wird tienen un cambio vocálico inesperado e→i.",
    },
    conjugations: [
      c("ich",       "werde",  "werd",  "e",    ""),
      c("du",        "wirst",  "w",     "irst",  "", true),
      c("er/sie/es", "wird",   "w",     "ird",   "", true),
      c("wir",       "werden", "werd",  "en",    ""),
      c("ihr",       "werdet", "werd",  "et",    ""),
      c("sie/Sie",   "werden", "werd",  "en",    ""),
    ],
  },
  {
    id: 4,
    infinitive: "können",
    en: "can / to be able to",
    es: "poder",
    pattern: { en: "Modal: ö → a (singular)", es: "Modal: ö → a (singular)" },
    note: {
      en: "Modal verbs: ich and er/sie/es share the same form with no ending. Singular stem kann- (ö→a), plural könn-.",
      es: "Verbos modales: ich y er/sie/es comparten la misma forma sin terminación. Singular kann- (ö→a), plural könn-.",
    },
    conjugations: [
      c("ich",       "kann",   "k",  "a",  "nn",   true),
      c("du",        "kannst", "k",  "a",  "nnst", true),
      c("er/sie/es", "kann",   "k",  "a",  "nn",   true),
      c("wir",       "können", "k",  "ö",  "nnen"),
      c("ihr",       "könnt",  "k",  "ö",  "nnt"),
      c("sie/Sie",   "können", "k",  "ö",  "nnen"),
    ],
  },
  {
    id: 5,
    infinitive: "müssen",
    en: "must / to have to",
    es: "tener que / deber",
    pattern: { en: "Modal: ü → u (singular)", es: "Modal: ü → u (singular)" },
    note: {
      en: "Singular stem muss- (umlaut dropped), plural müss-. Ich muss and er muss have no personal ending.",
      es: "Singular muss- (sin umlaut), plural müss-. Ich muss y er muss no llevan terminación personal.",
    },
    conjugations: [
      c("ich",       "muss",   "m",  "u",  "ss",   true),
      c("du",        "musst",  "m",  "u",  "sst",  true),
      c("er/sie/es", "muss",   "m",  "u",  "ss",   true),
      c("wir",       "müssen", "m",  "ü",  "ssen"),
      c("ihr",       "müsst",  "m",  "ü",  "sst"),
      c("sie/Sie",   "müssen", "m",  "ü",  "ssen"),
    ],
  },
  {
    id: 6,
    infinitive: "wollen",
    en: "to want",
    es: "querer",
    pattern: { en: "Modal: o → i (singular)", es: "Modal: o → i (singular)" },
    note: {
      en: "Singular stem will- (o→i, no umlaut), plural woll-. One of the most-used modal verbs.",
      es: "Singular will- (o→i, sin umlaut), plural woll-. Uno de los modales más usados.",
    },
    conjugations: [
      c("ich",       "will",   "w",  "i",  "ll",   true),
      c("du",        "willst", "w",  "i",  "llst", true),
      c("er/sie/es", "will",   "w",  "i",  "ll",   true),
      c("wir",       "wollen", "w",  "o",  "llen"),
      c("ihr",       "wollt",  "w",  "o",  "llt"),
      c("sie/Sie",   "wollen", "w",  "o",  "llen"),
    ],
  },
  {
    id: 7,
    infinitive: "dürfen",
    en: "may / to be allowed to",
    es: "poder (permiso) / tener permitido",
    pattern: { en: "Modal: ü → a (singular)", es: "Modal: ü → a (singular)" },
    note: {
      en: "Singular stem darf- (ü→a), plural dürf-. Used to express permission or prohibition.",
      es: "Singular darf- (ü→a), plural dürf-. Expresa permiso o prohibición.",
    },
    conjugations: [
      c("ich",       "darf",   "d",  "a",  "rf",   true),
      c("du",        "darfst", "d",  "a",  "rfst", true),
      c("er/sie/es", "darf",   "d",  "a",  "rf",   true),
      c("wir",       "dürfen", "d",  "ü",  "rfen"),
      c("ihr",       "dürft",  "d",  "ü",  "rft"),
      c("sie/Sie",   "dürfen", "d",  "ü",  "rfen"),
    ],
  },
  {
    id: 8,
    infinitive: "mögen",
    en: "to like",
    es: "gustar / querer",
    pattern: { en: "Modal: ö → a (singular)", es: "Modal: ö → a (singular)" },
    note: {
      en: "Singular mag (ö→a), plural mög-. The subjunctive form möchte (would like) is extremely common.",
      es: "Singular mag (ö→a), plural mög-. La forma subjuntiva möchte (me gustaría) es muy común.",
    },
    conjugations: [
      c("ich",       "mag",    "m",  "a",  "g",   true),
      c("du",        "magst",  "m",  "a",  "gst", true),
      c("er/sie/es", "mag",    "m",  "a",  "g",   true),
      c("wir",       "mögen",  "m",  "ö",  "gen"),
      c("ihr",       "mögt",   "m",  "ö",  "gt"),
      c("sie/Sie",   "mögen",  "m",  "ö",  "gen"),
    ],
  },
  {
    id: 9,
    infinitive: "fahren",
    en: "to drive / to travel",
    es: "conducir / viajar",
    pattern: { en: "Strong: a → ä (du / er)", es: "Fuerte: a → ä (du / er)" },
    note: {
      en: "The stem vowel -a- becomes -ä- (umlaut) only in 2nd and 3rd person singular. Wir/ihr/sie stay the same.",
      es: "La vocal -a- del stem se convierte en -ä- (umlaut) solo en 2.ª y 3.ª persona del singular.",
    },
    conjugations: [
      c("ich",       "fahre",  "fahr", "e",   ""),
      c("du",        "fährst", "f",    "ä",   "hrst", true),
      c("er/sie/es", "fährt",  "f",    "ä",   "hrt",  true),
      c("wir",       "fahren", "fahr", "en",  ""),
      c("ihr",       "fahrt",  "fahr", "t",   ""),
      c("sie/Sie",   "fahren", "fahr", "en",  ""),
    ],
  },
  {
    id: 10,
    infinitive: "laufen",
    en: "to run / to walk",
    es: "correr / caminar",
    pattern: { en: "Strong: au → äu (du / er)", es: "Fuerte: au → äu (du / er)" },
    note: {
      en: "The diphthong -au- gets an umlaut → -äu- in 2nd and 3rd person singular.",
      es: "El diptongo -au- toma umlaut → -äu- en 2.ª y 3.ª persona del singular.",
    },
    conjugations: [
      c("ich",       "laufe",  "lauf", "e",    ""),
      c("du",        "läufst", "l",    "äu",   "fst", true),
      c("er/sie/es", "läuft",  "l",    "äu",   "ft",  true),
      c("wir",       "laufen", "lauf", "en",   ""),
      c("ihr",       "lauft",  "lauf", "t",    ""),
      c("sie/Sie",   "laufen", "lauf", "en",   ""),
    ],
  },
  {
    id: 11,
    infinitive: "sehen",
    en: "to see",
    es: "ver",
    pattern: { en: "Strong: e → ie (du / er)", es: "Fuerte: e → ie (du / er)" },
    note: {
      en: "The short -e- in the stem lengthens to -ie- in 2nd and 3rd person singular.",
      es: "La -e- corta del stem se alarga a -ie- en 2.ª y 3.ª persona del singular.",
    },
    conjugations: [
      c("ich",       "sehe",   "seh",  "e",   ""),
      c("du",        "siehst", "s",    "ie",  "hst", true),
      c("er/sie/es", "sieht",  "s",    "ie",  "ht",  true),
      c("wir",       "sehen",  "seh",  "en",  ""),
      c("ihr",       "seht",   "seh",  "t",   ""),
      c("sie/Sie",   "sehen",  "seh",  "en",  ""),
    ],
  },
  {
    id: 12,
    infinitive: "lesen",
    en: "to read",
    es: "leer",
    pattern: { en: "Strong: e → ie (du / er)", es: "Fuerte: e → ie (du / er)" },
    note: {
      en: "Same e→ie pattern as sehen. Du liest, not *du liesst — the double-s contracts after a long vowel.",
      es: "Mismo patrón e→ie que sehen. Du liest, no *du liesst — la doble s se contrae tras vocal larga.",
    },
    conjugations: [
      c("ich",       "lese",   "les",  "e",   ""),
      c("du",        "liest",  "l",    "ie",  "st", true),
      c("er/sie/es", "liest",  "l",    "ie",  "st", true),
      c("wir",       "lesen",  "les",  "en",  ""),
      c("ihr",       "lest",   "les",  "t",   ""),
      c("sie/Sie",   "lesen",  "les",  "en",  ""),
    ],
  },
  {
    id: 13,
    infinitive: "sprechen",
    en: "to speak",
    es: "hablar",
    pattern: { en: "Strong: e → i (du / er)", es: "Fuerte: e → i (du / er)" },
    note: {
      en: "The short -e- in the stem becomes -i- in du/er. This e→i shift is the most common strong verb pattern.",
      es: "La -e- corta del stem se convierte en -i- en du/er. Este cambio e→i es el patrón de verbo fuerte más común.",
    },
    conjugations: [
      c("ich",       "spreche",  "sprech",  "e",   ""),
      c("du",        "sprichst", "spr",     "i",   "chst", true),
      c("er/sie/es", "spricht",  "spr",     "i",   "cht",  true),
      c("wir",       "sprechen", "sprech",  "en",  ""),
      c("ihr",       "sprecht",  "sprech",  "t",   ""),
      c("sie/Sie",   "sprechen", "sprech",  "en",  ""),
    ],
  },
  {
    id: 14,
    infinitive: "essen",
    en: "to eat",
    es: "comer",
    pattern: { en: "Strong: e → i (du / er)", es: "Fuerte: e → i (du / er)" },
    note: {
      en: "Stem ess- becomes iss- in du/er. Du isst (not *du issst) — German avoids triple consonants.",
      es: "El stem ess- se convierte en iss- en du/er. Du isst (no *du issst) — el alemán evita triple consonante.",
    },
    conjugations: [
      c("ich",       "esse",   "ess",  "e",    ""),
      c("du",        "isst",   "",     "i",    "sst", true),
      c("er/sie/es", "isst",   "",     "i",    "sst", true),
      c("wir",       "essen",  "ess",  "en",   ""),
      c("ihr",       "esst",   "ess",  "t",    ""),
      c("sie/Sie",   "essen",  "ess",  "en",   ""),
    ],
  },
  {
    id: 15,
    infinitive: "geben",
    en: "to give",
    es: "dar",
    pattern: { en: "Strong: e → i (du / er)", es: "Fuerte: e → i (du / er)" },
    note: {
      en: "Stem geb- becomes gib- in du/er. One of the most frequent strong verbs in everyday speech.",
      es: "El stem geb- se convierte en gib- en du/er. Uno de los verbos fuertes más frecuentes del habla cotidiana.",
    },
    conjugations: [
      c("ich",       "gebe",   "geb",  "e",    ""),
      c("du",        "gibst",  "g",    "i",    "bst", true),
      c("er/sie/es", "gibt",   "g",    "i",    "bt",  true),
      c("wir",       "geben",  "geb",  "en",   ""),
      c("ihr",       "gebt",   "geb",  "t",    ""),
      c("sie/Sie",   "geben",  "geb",  "en",   ""),
    ],
  },
  {
    id: 16,
    infinitive: "nehmen",
    en: "to take",
    es: "tomar / coger",
    pattern: { en: "Strong: nehm → nimm (du / er)", es: "Fuerte: nehm → nimm (du / er)" },
    note: {
      en: "One of the most irregular strong verbs: stem nehm- becomes nimm- (vowel change e→i + consonant doubling).",
      es: "Uno de los verbos fuertes más irregulares: el stem nehm- se convierte en nimm- (cambio e→i + consonante doble).",
    },
    conjugations: [
      c("ich",       "nehme",  "nehm", "e",    ""),
      c("du",        "nimmst", "n",    "imm",  "st", true),
      c("er/sie/es", "nimmt",  "n",    "imm",  "t",  true),
      c("wir",       "nehmen", "nehm", "en",   ""),
      c("ihr",       "nehmt",  "nehm", "t",    ""),
      c("sie/Sie",   "nehmen", "nehm", "en",   ""),
    ],
  },
  {
    id: 17,
    infinitive: "schlafen",
    en: "to sleep",
    es: "dormir",
    pattern: { en: "Strong: a → ä (du / er)", es: "Fuerte: a → ä (du / er)" },
    note: {
      en: "Same a→ä umlaut pattern as fahren. Only affects 2nd and 3rd person singular.",
      es: "Mismo patrón a→ä que fahren. Solo afecta a la 2.ª y 3.ª persona del singular.",
    },
    conjugations: [
      c("ich",       "schlafe",  "schlaf", "e",    ""),
      c("du",        "schläfst", "schl",   "ä",    "fst", true),
      c("er/sie/es", "schläft",  "schl",   "ä",    "ft",  true),
      c("wir",       "schlafen", "schlaf", "en",   ""),
      c("ihr",       "schlaft",  "schlaf", "t",    ""),
      c("sie/Sie",   "schlafen", "schlaf", "en",   ""),
    ],
  },
  {
    id: 18,
    infinitive: "wissen",
    en: "to know (a fact)",
    es: "saber",
    pattern: { en: "Preterite-present: weiß (1st / 3rd sg)", es: "Pretérito-presente: weiß (1.ª / 3.ª sg)" },
    note: {
      en: "A preterite-present verb like modals: ich weiß / er weiß share the same form with no ending. Plural: wiss-.",
      es: "Verbo pretérito-presente como los modales: ich weiß / er weiß comparten forma sin terminación. Plural: wiss-.",
    },
    conjugations: [
      c("ich",       "weiß",   "w",    "ei",  "ß",   true),
      c("du",        "weißt",  "w",    "ei",  "ßt",  true),
      c("er/sie/es", "weiß",   "w",    "ei",  "ß",   true),
      c("wir",       "wissen", "wiss", "en",  ""),
      c("ihr",       "wisst",  "wiss", "t",   ""),
      c("sie/Sie",   "wissen", "wiss", "en",  ""),
    ],
  },
];
