// Germany map data: 16 federal states (Bundesländer) + major cities
// SVG polygon points mapped to a 500x560 viewBox

export const GERMAN_STATES = [
  {
    id: "schleswig-holstein",
    name: "Schleswig-Holstein",
    nameEn: "Schleswig-Holstein",
    ipa: "[ˈʃleːsvɪç ˈhɔlʃtaɪn]",
    capital: "Kiel",
    capitalIpa: "[kiːl]",
    color: "#5B9BD5",
    hoverColor: "#3A7BC8",
    polygon: "130,10 270,5 295,50 260,85 235,110 175,115 130,95 110,55",
    labelX: 190,
    labelY: 60,
    fact: { en: "Germany's northernmost state, bordering Denmark", es: "Estado más al norte de Alemania, limita con Dinamarca" },
    cities: ["Kiel", "Lübeck", "Flensburg"]
  },
  {
    id: "hamburg",
    name: "Hamburg",
    nameEn: "Hamburg",
    ipa: "[ˈhambʊʁk]",
    capital: "Hamburg",
    capitalIpa: "[ˈhambʊʁk]",
    color: "#E74C3C",
    hoverColor: "#C0392B",
    polygon: "202,102 238,102 238,127 202,127",
    labelX: 220,
    labelY: 117,
    fact: { en: "Germany's largest port city and second-largest city", es: "La ciudad portuaria más grande de Alemania y segunda ciudad más grande" },
    cities: ["Hamburg"]
  },
  {
    id: "mecklenburg-vorpommern",
    name: "Mecklenburg-Vorpommern",
    nameEn: "Mecklenburg-Western Pomerania",
    ipa: "[ˈmɛklənbʊʁk ˈfoːɐ̯pɔmɐn]",
    capital: "Schwerin",
    capitalIpa: "[ʃveˈʁiːn]",
    color: "#27AE60",
    hoverColor: "#1E8449",
    polygon: "238,85 480,15 485,110 300,108 265,90",
    labelX: 370,
    labelY: 70,
    fact: { en: "Known for its Baltic Sea coast and over 2,000 lakes", es: "Conocido por su costa del Mar Báltico y más de 2.000 lagos" },
    cities: ["Schwerin", "Rostock", "Stralsund"]
  },
  {
    id: "bremen",
    name: "Bremen",
    nameEn: "Bremen",
    ipa: "[ˈbʁeːmən]",
    capital: "Bremen",
    capitalIpa: "[ˈbʁeːmən]",
    color: "#9B59B6",
    hoverColor: "#7D3C98",
    polygon: "128,172 156,172 156,192 128,192",
    labelX: 142,
    labelY: 184,
    fact: { en: "Germany's smallest state and oldest port city", es: "El estado más pequeño de Alemania y su ciudad portuaria más antigua" },
    cities: ["Bremen", "Bremerhaven"]
  },
  {
    id: "niedersachsen",
    name: "Niedersachsen",
    nameEn: "Lower Saxony",
    ipa: "[ˈniːdɐˌzaksən]",
    capital: "Hannover",
    capitalIpa: "[haˈnoːfɐ]",
    color: "#F39C12",
    hoverColor: "#D68910",
    polygon: "80,120 202,127 238,127 235,172 156,172 156,192 133,192 130,178 105,228 65,268 0,258 0,178 78,168",
    labelX: 120,
    labelY: 185,
    fact: { en: "The second-largest German state by area, home to the Harz mountains", es: "El segundo estado alemán más grande por área, hogar de las montañas Harz" },
    cities: ["Hannover", "Braunschweig", "Osnabrück", "Oldenburg"]
  },
  {
    id: "nordrhein-westfalen",
    name: "Nordrhein-Westfalen",
    nameEn: "North Rhine-Westphalia",
    ipa: "[ˈnɔʁtʁaɪn ˈvɛstfaːlən]",
    capital: "Düsseldorf",
    capitalIpa: "[ˈdʏsəldɔʁf]",
    color: "#1ABC9C",
    hoverColor: "#17A589",
    polygon: "0,255 130,232 162,248 168,288 148,325 103,338 55,318 0,285",
    labelX: 80,
    labelY: 285,
    fact: { en: "Germany's most populous state with over 18 million residents", es: "El estado más poblado de Alemania con más de 18 millones de habitantes" },
    cities: ["Düsseldorf", "Köln", "Dortmund", "Essen", "Bonn"]
  },
  {
    id: "sachsen-anhalt",
    name: "Sachsen-Anhalt",
    nameEn: "Saxony-Anhalt",
    ipa: "[ˈzaksən ˈanˌhalt]",
    capital: "Magdeburg",
    capitalIpa: "[ˈmaːkdəbʊʁk]",
    color: "#E67E22",
    hoverColor: "#CA6F1E",
    polygon: "218,168 285,162 312,192 318,245 268,255 228,238",
    labelX: 263,
    labelY: 210,
    fact: { en: "Home to the famous Lutherstadt Wittenberg where Martin Luther began the Reformation", es: "Hogar de la famosa Lutherstadt Wittenberg donde Martín Lutero comenzó la Reforma" },
    cities: ["Magdeburg", "Halle", "Dessau"]
  },
  {
    id: "brandenburg",
    name: "Brandenburg",
    nameEn: "Brandenburg",
    ipa: "[ˈbʁandənbʊʁk]",
    capital: "Potsdam",
    capitalIpa: "[ˈpɔtsdam]",
    color: "#85C1E9",
    hoverColor: "#5DADE2",
    polygon: "288,112 483,118 490,285 402,285 362,242 312,192 285,162 288,155",
    labelX: 395,
    labelY: 195,
    fact: { en: "Surrounds Berlin and is known for its forests and lakes", es: "Rodea Berlín y es conocido por sus bosques y lagos" },
    cities: ["Potsdam", "Brandenburg an der Havel", "Cottbus"]
  },
  {
    id: "berlin",
    name: "Berlin",
    nameEn: "Berlin",
    ipa: "[bɛʁˈliːn]",
    capital: "Berlin",
    capitalIpa: "[bɛʁˈliːn]",
    color: "#E74C3C",
    hoverColor: "#C0392B",
    polygon: "346,168 382,168 382,198 346,198",
    labelX: 364,
    labelY: 185,
    fact: { en: "Germany's capital and largest city, reunified in 1990", es: "Capital y ciudad más grande de Alemania, reunificada en 1990" },
    cities: ["Berlin"]
  },
  {
    id: "sachsen",
    name: "Sachsen",
    nameEn: "Saxony",
    ipa: "[ˈzaksən]",
    capital: "Dresden",
    capitalIpa: "[ˈdʁeːzdən]",
    color: "#A569BD",
    hoverColor: "#8E44AD",
    polygon: "318,245 395,248 408,288 382,342 328,348 312,302",
    labelX: 360,
    labelY: 298,
    fact: { en: "Known for Dresden's baroque architecture and Meissen porcelain", es: "Conocido por la arquitectura barroca de Dresde y la porcelana de Meissen" },
    cities: ["Dresden", "Leipzig", "Chemnitz"]
  },
  {
    id: "thueringen",
    name: "Thüringen",
    nameEn: "Thuringia",
    ipa: "[ˈtyːʁɪŋən]",
    capital: "Erfurt",
    capitalIpa: "[ˈɛʁfʊʁt]",
    color: "#52BE80",
    hoverColor: "#27AE60",
    polygon: "228,252 318,245 318,288 298,315 242,322 222,302",
    labelX: 270,
    labelY: 290,
    fact: { en: "Called the 'Green Heart of Germany' for its dense forests", es: "Llamado el 'Corazón Verde de Alemania' por sus densos bosques" },
    cities: ["Erfurt", "Weimar", "Jena"]
  },
  {
    id: "hessen",
    name: "Hessen",
    nameEn: "Hesse",
    ipa: "[ˈhɛsən]",
    capital: "Wiesbaden",
    capitalIpa: "[ˈviːsˌbaːdən]",
    color: "#F1C40F",
    hoverColor: "#D4AC0D",
    polygon: "152,282 222,258 245,268 248,335 228,372 178,382 150,355",
    labelX: 195,
    labelY: 320,
    fact: { en: "Home to Frankfurt, Germany's financial capital and major airport hub", es: "Hogar de Frankfurt, la capital financiera de Alemania y un importante hub aeroportuario" },
    cities: ["Wiesbaden", "Frankfurt", "Kassel", "Darmstadt"]
  },
  {
    id: "rheinland-pfalz",
    name: "Rheinland-Pfalz",
    nameEn: "Rhineland-Palatinate",
    ipa: "[ˈʁaɪnlant ˈp͡falt͡s]",
    capital: "Mainz",
    capitalIpa: "[maɪnts]",
    color: "#5DADE2",
    hoverColor: "#2E86C1",
    polygon: "55,318 152,325 178,382 162,422 112,442 60,402 40,358",
    labelX: 105,
    labelY: 375,
    fact: { en: "Famous for the Rhine Valley, wine regions, and Nürburgring racetrack", es: "Famoso por el valle del Rin, las regiones vinícolas y el circuito de Nürburgring" },
    cities: ["Mainz", "Koblenz", "Trier", "Kaiserslautern"]
  },
  {
    id: "saarland",
    name: "Saarland",
    nameEn: "Saarland",
    ipa: "[ˈzaːɐ̯lant]",
    capital: "Saarbrücken",
    capitalIpa: "[ˈzaːɐ̯ˌbʁʏkən]",
    color: "#EC407A",
    hoverColor: "#C2185B",
    polygon: "58,402 110,402 110,432 58,432",
    labelX: 84,
    labelY: 420,
    fact: { en: "Germany's smallest non-city state, bordering France and Luxembourg", es: "El estado no-ciudad más pequeño de Alemania, limita con Francia y Luxemburgo" },
    cities: ["Saarbrücken", "Neunkirchen"]
  },
  {
    id: "baden-wuerttemberg",
    name: "Baden-Württemberg",
    nameEn: "Baden-Württemberg",
    ipa: "[ˈbaːdən ˈvʏʁtəmbɛʁk]",
    capital: "Stuttgart",
    capitalIpa: "[ˈʃtʊtɡaʁt]",
    color: "#FF8A65",
    hoverColor: "#E64A19",
    polygon: "110,432 178,382 228,388 235,448 208,492 148,498 100,452",
    labelX: 168,
    labelY: 445,
    fact: { en: "Home to the Black Forest, Heidelberg Castle, and the Mercedes-Benz museum", es: "Hogar de la Selva Negra, el castillo de Heidelberg y el museo Mercedes-Benz" },
    cities: ["Stuttgart", "Karlsruhe", "Freiburg", "Heidelberg", "Mannheim"]
  },
  {
    id: "bayern",
    name: "Bayern",
    nameEn: "Bavaria",
    ipa: "[ˈbaɪɐn]",
    capital: "München",
    capitalIpa: "[ˈmʏnçən]",
    color: "#42A5F5",
    hoverColor: "#1E88E5",
    polygon: "238,325 382,342 408,288 452,322 462,392 428,468 362,512 278,512 228,470 228,400",
    labelX: 345,
    labelY: 415,
    fact: { en: "Germany's largest state, home to Oktoberfest, the Alps, and Neuschwanstein Castle", es: "El estado más grande de Alemania, sede del Oktoberfest, los Alpes y el castillo de Neuschwanstein" },
    cities: ["München", "Nürnberg", "Augsburg", "Regensburg", "Würzburg"]
  }
];

export const GERMANY_CITIES = [
  { id: 1, name: "Berlin", ipa: "[bɛʁˈliːn]", state: "Berlin", stateId: "berlin", x: 364, y: 183, population: "3.7M", fact: { en: "Capital of Germany, famous for the Brandenburg Gate and Berlin Wall history", es: "Capital de Alemania, famosa por la Puerta de Brandeburgo y la historia del Muro de Berlín" } },
  { id: 2, name: "Hamburg", ipa: "[ˈhambʊʁk]", state: "Hamburg", stateId: "hamburg", x: 220, y: 115, population: "1.9M", fact: { en: "Germany's largest port city, known for the Speicherstadt warehouse district", es: "La ciudad portuaria más grande de Alemania, conocida por el distrito de almacenes Speicherstadt" } },
  { id: 3, name: "München", ipa: "[ˈmʏnçən]", state: "Bayern", stateId: "bayern", x: 322, y: 468, population: "1.5M", fact: { en: "Capital of Bavaria, home to Oktoberfest and the BMW Museum", es: "Capital de Baviera, sede del Oktoberfest y el museo BMW" } },
  { id: 4, name: "Köln", ipa: "[kœln]", state: "Nordrhein-Westfalen", stateId: "nordrhein-westfalen", x: 90, y: 298, population: "1.1M", fact: { en: "Famous for its magnificent Gothic cathedral (Kölner Dom)", es: "Famosa por su magnífica catedral gótica (Kölner Dom)" } },
  { id: 5, name: "Frankfurt", ipa: "[ˈfʁaŋkfʊʁt]", state: "Hessen", stateId: "hessen", x: 185, y: 325, population: "765K", fact: { en: "Germany's financial hub, home to the European Central Bank", es: "El centro financiero de Alemania, sede del Banco Central Europeo" } },
  { id: 6, name: "Stuttgart", ipa: "[ˈʃtʊtɡaʁt]", state: "Baden-Württemberg", stateId: "baden-wuerttemberg", x: 165, y: 435, population: "635K", fact: { en: "Home to Mercedes-Benz and Porsche headquarters and museums", es: "Sede de los cuarteles generales y museos de Mercedes-Benz y Porsche" } },
  { id: 7, name: "Düsseldorf", ipa: "[ˈdʏsəldɔʁf]", state: "Nordrhein-Westfalen", stateId: "nordrhein-westfalen", x: 80, y: 272, population: "620K", fact: { en: "Capital of NRW, known for its fashion scene and art galleries", es: "Capital de Renania del Norte-Westfalia, conocida por su escena de moda y galerías de arte" } },
  { id: 8, name: "Dresden", ipa: "[ˈdʁeːzdən]", state: "Sachsen", stateId: "sachsen", x: 378, y: 302, population: "555K", fact: { en: "Called 'Florence of the Elbe' for its baroque architecture", es: "Llamada la 'Florencia del Elba' por su arquitectura barroca" } },
  { id: 9, name: "Leipzig", ipa: "[ˈlaɪptsɪç]", state: "Sachsen", stateId: "sachsen", x: 335, y: 265, population: "620K", fact: { en: "Cultural city where Bach and Mendelssohn composed their great works", es: "Ciudad cultural donde Bach y Mendelssohn compusieron sus grandes obras" } },
  { id: 10, name: "Hannover", ipa: "[haˈnoːfɐ]", state: "Niedersachsen", stateId: "niedersachsen", x: 188, y: 188, population: "540K", fact: { en: "Hosts the world's largest industrial trade fair (Hannover Messe)", es: "Alberga la feria industrial más grande del mundo (Hannover Messe)" } },
  { id: 11, name: "Nürnberg", ipa: "[ˈnʏʁnbɛʁk]", state: "Bayern", stateId: "bayern", x: 305, y: 388, population: "520K", fact: { en: "Famous for its medieval castle and the Nuremberg Christmas Market", es: "Famosa por su castillo medieval y el Mercado de Navidad de Núremberg" } },
  { id: 12, name: "Bonn", ipa: "[bɔn]", state: "Nordrhein-Westfalen", stateId: "nordrhein-westfalen", x: 78, y: 315, population: "330K", fact: { en: "Beethoven's birthplace and former capital of West Germany", es: "Ciudad natal de Beethoven y antigua capital de Alemania Occidental" } },
  { id: 13, name: "Potsdam", ipa: "[ˈpɔtsdam]", state: "Brandenburg", stateId: "brandenburg", x: 350, y: 208, population: "185K", fact: { en: "City of palaces and gardens, including the famous Sanssouci Palace", es: "Ciudad de palacios y jardines, incluyendo el famoso Palacio de Sanssouci" } },
  { id: 14, name: "Kiel", ipa: "[kiːl]", state: "Schleswig-Holstein", stateId: "schleswig-holstein", x: 218, y: 48, population: "245K", fact: { en: "Major Baltic Sea port city and hosts the annual Kiel Week sailing event", es: "Importante ciudad portuaria del Mar Báltico y sede de la Semana de Kiel" } },
  { id: 15, name: "Erfurt", ipa: "[ˈɛʁfʊʁt]", state: "Thüringen", stateId: "thueringen", x: 262, y: 290, population: "214K", fact: { en: "Medieval city famous for its cathedral and Merchants' Bridge", es: "Ciudad medieval famosa por su catedral y el Puente de los Comerciantes" } },
  { id: 16, name: "Freiburg", ipa: "[ˈfʁaɪbʊʁk]", state: "Baden-Württemberg", stateId: "baden-wuerttemberg", x: 135, y: 472, population: "228K", fact: { en: "Gateway to the Black Forest, sunniest city in Germany", es: "Puerta de entrada a la Selva Negra, la ciudad más soleada de Alemania" } }
];
