// German verbs & present-tense conjugations (from class whiteboard)
// Pronouns order: ich | du | er/sie/es | wir | ihr | sie/Sie

export const PRONOUNS = ['ich', 'du', 'er/sie/es', 'wir', 'ihr', 'sie/Sie'];

export const GERMAN_VERBS = [
  // ── Very irregular ─────────────────────────────────────────────────────────
  {
    id: 1,
    infinitive: 'sein',
    en: 'to be',
    es: 'ser / estar',
    type: 'irregular',
    stemChange: null,
    note: { en: 'Highly irregular — must be memorized', es: 'Muy irregular — hay que memorizarlo' },
    forms: {
      'ich':      { form: 'bin',   highlight: true },
      'du':       { form: 'bist',  highlight: true },
      'er/sie/es':{ form: 'ist',   highlight: true },
      'wir':      { form: 'sind',  highlight: true },
      'ihr':      { form: 'seid',  highlight: true },
      'sie/Sie':  { form: 'sind',  highlight: true },
    },
  },
  {
    id: 2,
    infinitive: 'haben',
    en: 'to have',
    es: 'tener',
    type: 'irregular',
    stemChange: null,
    note: { en: 'Irregular in du and er/sie/es forms', es: 'Irregular en las formas du y er/sie/es' },
    forms: {
      'ich':      { form: 'habe',  highlight: false },
      'du':       { form: 'hast',  highlight: true  },
      'er/sie/es':{ form: 'hat',   highlight: true  },
      'wir':      { form: 'haben', highlight: false },
      'ihr':      { form: 'habt',  highlight: false },
      'sie/Sie':  { form: 'haben', highlight: false },
    },
  },
  // ── Stem-vowel change e → i ─────────────────────────────────────────────
  {
    id: 3,
    infinitive: 'essen',
    en: 'to eat',
    es: 'comer',
    type: 'irregular',
    stemChange: 'e → i',
    note: { en: 'Stem vowel changes e → i in du and er/sie/es', es: 'La vocal del radical cambia e → i en du y er/sie/es' },
    forms: {
      'ich':      { form: 'esse',  highlight: false },
      'du':       { form: 'isst',  highlight: true  },
      'er/sie/es':{ form: 'isst',  highlight: true  },
      'wir':      { form: 'essen', highlight: false },
      'ihr':      { form: 'esst',  highlight: false },
      'sie/Sie':  { form: 'essen', highlight: false },
    },
  },
  {
    id: 4,
    infinitive: 'sprechen',
    en: 'to speak',
    es: 'hablar',
    type: 'irregular',
    stemChange: 'e → i',
    note: { en: 'Stem vowel changes e → i in du and er/sie/es', es: 'La vocal del radical cambia e → i en du y er/sie/es' },
    forms: {
      'ich':      { form: 'spreche',  highlight: false },
      'du':       { form: 'sprichst', highlight: true  },
      'er/sie/es':{ form: 'spricht',  highlight: true  },
      'wir':      { form: 'sprechen', highlight: false },
      'ihr':      { form: 'sprecht',  highlight: false },
      'sie/Sie':  { form: 'sprechen', highlight: false },
    },
  },
  // ── Stem-vowel change e → ie ────────────────────────────────────────────
  {
    id: 5,
    infinitive: 'sehen',
    en: 'to see',
    es: 'ver',
    type: 'irregular',
    stemChange: 'e → ie',
    note: { en: 'Stem vowel changes e → ie in du and er/sie/es', es: 'La vocal del radical cambia e → ie en du y er/sie/es' },
    forms: {
      'ich':      { form: 'sehe',   highlight: false },
      'du':       { form: 'siehst', highlight: true  },
      'er/sie/es':{ form: 'sieht',  highlight: true  },
      'wir':      { form: 'sehen',  highlight: false },
      'ihr':      { form: 'seht',   highlight: false },
      'sie/Sie':  { form: 'sehen',  highlight: false },
    },
  },
  {
    id: 6,
    infinitive: 'lesen',
    en: 'to read',
    es: 'leer',
    type: 'irregular',
    stemChange: 'e → ie',
    note: { en: 'Stem vowel changes e → ie in du and er/sie/es', es: 'La vocal del radical cambia e → ie en du y er/sie/es' },
    forms: {
      'ich':      { form: 'lese',  highlight: false },
      'du':       { form: 'liest', highlight: true  },
      'er/sie/es':{ form: 'liest', highlight: true  },
      'wir':      { form: 'lesen', highlight: false },
      'ihr':      { form: 'lest',  highlight: false },
      'sie/Sie':  { form: 'lesen', highlight: false },
    },
  },
  // ── Regular verbs ───────────────────────────────────────────────────────
  {
    id: 7,
    infinitive: 'gehen',
    en: 'to go',
    es: 'ir',
    type: 'regular',
    stemChange: null,
    note: null,
    forms: {
      'ich':      { form: 'gehe',   highlight: false },
      'du':       { form: 'gehst',  highlight: false },
      'er/sie/es':{ form: 'geht',   highlight: false },
      'wir':      { form: 'gehen',  highlight: false },
      'ihr':      { form: 'geht',   highlight: false },
      'sie/Sie':  { form: 'gehen',  highlight: false },
    },
  },
  {
    id: 8,
    infinitive: 'reisen',
    en: 'to travel',
    es: 'viajar',
    type: 'regular',
    stemChange: null,
    note: null,
    forms: {
      'ich':      { form: 'reise',   highlight: false },
      'du':       { form: 'reist',   highlight: false },
      'er/sie/es':{ form: 'reist',   highlight: false },
      'wir':      { form: 'reisen',  highlight: false },
      'ihr':      { form: 'reist',   highlight: false },
      'sie/Sie':  { form: 'reisen',  highlight: false },
    },
  },
  {
    id: 9,
    infinitive: 'singen',
    en: 'to sing',
    es: 'cantar',
    type: 'regular',
    stemChange: null,
    note: null,
    forms: {
      'ich':      { form: 'singe',   highlight: false },
      'du':       { form: 'singst',  highlight: false },
      'er/sie/es':{ form: 'singt',   highlight: false },
      'wir':      { form: 'singen',  highlight: false },
      'ihr':      { form: 'singt',   highlight: false },
      'sie/Sie':  { form: 'singen',  highlight: false },
    },
  },
  {
    id: 10,
    infinitive: 'fliegen',
    en: 'to fly',
    es: 'volar',
    type: 'regular',
    stemChange: null,
    note: null,
    forms: {
      'ich':      { form: 'fliege',   highlight: false },
      'du':       { form: 'fliegst',  highlight: false },
      'er/sie/es':{ form: 'fliegt',   highlight: false },
      'wir':      { form: 'fliegen',  highlight: false },
      'ihr':      { form: 'fliegt',   highlight: false },
      'sie/Sie':  { form: 'fliegen',  highlight: false },
    },
  },
  {
    id: 11,
    infinitive: 'spielen',
    en: 'to play',
    es: 'jugar',
    type: 'regular',
    stemChange: null,
    note: null,
    forms: {
      'ich':      { form: 'spiele',   highlight: false },
      'du':       { form: 'spielst',  highlight: false },
      'er/sie/es':{ form: 'spielt',   highlight: false },
      'wir':      { form: 'spielen',  highlight: false },
      'ihr':      { form: 'spielt',   highlight: false },
      'sie/Sie':  { form: 'spielen',  highlight: false },
    },
  },
  {
    id: 12,
    infinitive: 'joggen',
    en: 'to jog',
    es: 'trotar / hacer jogging',
    type: 'regular',
    stemChange: null,
    note: null,
    forms: {
      'ich':      { form: 'jogge',   highlight: false },
      'du':       { form: 'joggst',  highlight: false },
      'er/sie/es':{ form: 'joggt',   highlight: false },
      'wir':      { form: 'joggen',  highlight: false },
      'ihr':      { form: 'joggt',   highlight: false },
      'sie/Sie':  { form: 'joggen',  highlight: false },
    },
  },
  {
    id: 13,
    infinitive: 'trinken',
    en: 'to drink',
    es: 'beber / tomar',
    type: 'regular',
    stemChange: null,
    note: null,
    forms: {
      'ich':      { form: 'trinke',   highlight: false },
      'du':       { form: 'trinkst',  highlight: false },
      'er/sie/es':{ form: 'trinkt',   highlight: false },
      'wir':      { form: 'trinken',  highlight: false },
      'ihr':      { form: 'trinkt',   highlight: false },
      'sie/Sie':  { form: 'trinken',  highlight: false },
    },
  },
  {
    id: 14,
    infinitive: 'machen',
    en: 'to make / to do',
    es: 'hacer',
    type: 'regular',
    stemChange: null,
    note: null,
    forms: {
      'ich':      { form: 'mache',   highlight: false },
      'du':       { form: 'machst',  highlight: false },
      'er/sie/es':{ form: 'macht',   highlight: false },
      'wir':      { form: 'machen',  highlight: false },
      'ihr':      { form: 'macht',   highlight: false },
      'sie/Sie':  { form: 'machen',  highlight: false },
    },
  },
  {
    id: 15,
    infinitive: 'arbeiten',
    en: 'to work',
    es: 'trabajar',
    type: 'regular',
    stemChange: null,
    // arbeiten: stem ends in -t, so add -e- before -st and -t endings
    note: { en: 'Stem ends in -t: adds -e- before -st and -t endings', es: 'El radical termina en -t: se añade -e- antes de -st y -t' },
    forms: {
      'ich':      { form: 'arbeite',    highlight: false },
      'du':       { form: 'arbeitest',  highlight: true  },
      'er/sie/es':{ form: 'arbeitet',   highlight: true  },
      'wir':      { form: 'arbeiten',   highlight: false },
      'ihr':      { form: 'arbeitet',   highlight: true  },
      'sie/Sie':  { form: 'arbeiten',   highlight: false },
    },
  },
  // ── Stem-vowel change e → i (continued) ────────────────────────────────
  {
    id: 16,
    infinitive: 'treffen',
    en: 'to meet',
    es: 'encontrar / quedar con',
    type: 'irregular',
    stemChange: 'e → i',
    note: { en: 'Stem vowel changes e → i in du and er/sie/es', es: 'La vocal del radical cambia e → i en du y er/sie/es' },
    forms: {
      'ich':      { form: 'treffe',   highlight: false },
      'du':       { form: 'triffst',  highlight: true  },
      'er/sie/es':{ form: 'trifft',   highlight: true  },
      'wir':      { form: 'treffen',  highlight: false },
      'ihr':      { form: 'trefft',   highlight: false },
      'sie/Sie':  { form: 'treffen',  highlight: false },
    },
  },
  {
    id: 17,
    infinitive: 'geben',
    en: 'to give',
    es: 'dar',
    type: 'irregular',
    stemChange: 'e → i',
    note: { en: 'Stem vowel changes e → i in du and er/sie/es', es: 'La vocal del radical cambia e → i en du y er/sie/es' },
    forms: {
      'ich':      { form: 'gebe',   highlight: false },
      'du':       { form: 'gibst',  highlight: true  },
      'er/sie/es':{ form: 'gibt',   highlight: true  },
      'wir':      { form: 'geben',  highlight: false },
      'ihr':      { form: 'gebt',   highlight: false },
      'sie/Sie':  { form: 'geben',  highlight: false },
    },
  },
  {
    id: 18,
    infinitive: 'nehmen',
    en: 'to take',
    es: 'tomar / coger',
    type: 'irregular',
    stemChange: 'e → i',
    note: { en: 'e → i change + consonant shift (nehm- → nimm-) in du and er/sie/es', es: 'Cambio e → i y doble consonante (nehm- → nimm-) en du y er/sie/es' },
    forms: {
      'ich':      { form: 'nehme',   highlight: false },
      'du':       { form: 'nimmst',  highlight: true  },
      'er/sie/es':{ form: 'nimmt',   highlight: true  },
      'wir':      { form: 'nehmen',  highlight: false },
      'ihr':      { form: 'nehmt',   highlight: false },
      'sie/Sie':  { form: 'nehmen',  highlight: false },
    },
  },
  {
    id: 19,
    infinitive: 'helfen',
    en: 'to help',
    es: 'ayudar',
    type: 'irregular',
    stemChange: 'e → i',
    note: { en: 'Stem vowel changes e → i in du and er/sie/es', es: 'La vocal del radical cambia e → i en du y er/sie/es' },
    forms: {
      'ich':      { form: 'helfe',   highlight: false },
      'du':       { form: 'hilfst',  highlight: true  },
      'er/sie/es':{ form: 'hilft',   highlight: true  },
      'wir':      { form: 'helfen',  highlight: false },
      'ihr':      { form: 'helft',   highlight: false },
      'sie/Sie':  { form: 'helfen',  highlight: false },
    },
  },
  // ── Stem-vowel change a → ä ─────────────────────────────────────────────
  {
    id: 20,
    infinitive: 'fahren',
    en: 'to drive / travel',
    es: 'conducir / viajar en vehículo',
    type: 'irregular',
    stemChange: 'a → ä',
    note: { en: 'Stem vowel changes a → ä in du and er/sie/es', es: 'La vocal del radical cambia a → ä en du y er/sie/es' },
    forms: {
      'ich':      { form: 'fahre',   highlight: false },
      'du':       { form: 'fährst',  highlight: true  },
      'er/sie/es':{ form: 'fährt',   highlight: true  },
      'wir':      { form: 'fahren',  highlight: false },
      'ihr':      { form: 'fahrt',   highlight: false },
      'sie/Sie':  { form: 'fahren',  highlight: false },
    },
  },
  {
    id: 21,
    infinitive: 'schlafen',
    en: 'to sleep',
    es: 'dormir',
    type: 'irregular',
    stemChange: 'a → ä',
    note: { en: 'Stem vowel changes a → ä in du and er/sie/es', es: 'La vocal del radical cambia a → ä en du y er/sie/es' },
    forms: {
      'ich':      { form: 'schlafe',   highlight: false },
      'du':       { form: 'schläfst',  highlight: true  },
      'er/sie/es':{ form: 'schläft',   highlight: true  },
      'wir':      { form: 'schlafen',  highlight: false },
      'ihr':      { form: 'schlaft',   highlight: false },
      'sie/Sie':  { form: 'schlafen',  highlight: false },
    },
  },
  {
    id: 22,
    infinitive: 'laufen',
    en: 'to run / walk',
    es: 'correr / caminar',
    type: 'irregular',
    stemChange: 'au → äu',
    note: { en: 'Stem vowel changes au → äu in du and er/sie/es', es: 'La vocal del radical cambia au → äu en du y er/sie/es' },
    forms: {
      'ich':      { form: 'laufe',   highlight: false },
      'du':       { form: 'läufst',  highlight: true  },
      'er/sie/es':{ form: 'läuft',   highlight: true  },
      'wir':      { form: 'laufen',  highlight: false },
      'ihr':      { form: 'lauft',   highlight: false },
      'sie/Sie':  { form: 'laufen',  highlight: false },
    },
  },
  // ── Other key irregulars ────────────────────────────────────────────────
  {
    id: 23,
    infinitive: 'werden',
    en: 'to become',
    es: 'convertirse en / llegar a ser',
    type: 'irregular',
    stemChange: 'e → i',
    note: { en: 'Stem vowel changes e → i in du and er/sie/es; also used as future auxiliary', es: 'Cambio e → i en du y er/sie/es; también se usa como auxiliar de futuro' },
    forms: {
      'ich':      { form: 'werde',   highlight: false },
      'du':       { form: 'wirst',   highlight: true  },
      'er/sie/es':{ form: 'wird',    highlight: true  },
      'wir':      { form: 'werden',  highlight: false },
      'ihr':      { form: 'werdet',  highlight: false },
      'sie/Sie':  { form: 'werden',  highlight: false },
    },
  },
  {
    id: 24,
    infinitive: 'wissen',
    en: 'to know (a fact)',
    es: 'saber',
    type: 'irregular',
    stemChange: null,
    note: { en: 'Highly irregular: ich/er/sie/es use "weiß" (no ending); use for facts, not people', es: 'Muy irregular: ich/er/sie/es usan "weiß" (sin desinencia); se usa para hechos, no personas' },
    forms: {
      'ich':      { form: 'weiß',    highlight: true  },
      'du':       { form: 'weißt',   highlight: false },
      'er/sie/es':{ form: 'weiß',    highlight: true  },
      'wir':      { form: 'wissen',  highlight: false },
      'ihr':      { form: 'wisst',   highlight: false },
      'sie/Sie':  { form: 'wissen',  highlight: false },
    },
  },
  // ── Modal verbs ─────────────────────────────────────────────────────────
  {
    id: 25,
    infinitive: 'können',
    en: 'can / to be able to',
    es: 'poder',
    type: 'irregular',
    stemChange: null,
    note: { en: 'Modal: ich and er/sie/es share the same form (no ending); wir/sie/Sie return to infinitive', es: 'Modal: ich y er/sie/es comparten la misma forma (sin desinencia); wir/sie/Sie vuelven al infinitivo' },
    forms: {
      'ich':      { form: 'kann',    highlight: true  },
      'du':       { form: 'kannst',  highlight: false },
      'er/sie/es':{ form: 'kann',    highlight: true  },
      'wir':      { form: 'können',  highlight: false },
      'ihr':      { form: 'könnt',   highlight: false },
      'sie/Sie':  { form: 'können',  highlight: false },
    },
  },
  {
    id: 26,
    infinitive: 'müssen',
    en: 'must / to have to',
    es: 'tener que / deber',
    type: 'irregular',
    stemChange: null,
    note: { en: 'Modal: ich and er/sie/es share the same form (no ending)', es: 'Modal: ich y er/sie/es comparten la misma forma (sin desinencia)' },
    forms: {
      'ich':      { form: 'muss',    highlight: true  },
      'du':       { form: 'musst',   highlight: false },
      'er/sie/es':{ form: 'muss',    highlight: true  },
      'wir':      { form: 'müssen',  highlight: false },
      'ihr':      { form: 'müsst',   highlight: false },
      'sie/Sie':  { form: 'müssen',  highlight: false },
    },
  },
  {
    id: 27,
    infinitive: 'wollen',
    en: 'to want to',
    es: 'querer',
    type: 'irregular',
    stemChange: null,
    note: { en: 'Modal: ich and er/sie/es share the same form (no ending)', es: 'Modal: ich y er/sie/es comparten la misma forma (sin desinencia)' },
    forms: {
      'ich':      { form: 'will',    highlight: true  },
      'du':       { form: 'willst',  highlight: false },
      'er/sie/es':{ form: 'will',    highlight: true  },
      'wir':      { form: 'wollen',  highlight: false },
      'ihr':      { form: 'wollt',   highlight: false },
      'sie/Sie':  { form: 'wollen',  highlight: false },
    },
  },
  // ── Regular verbs (continued) ───────────────────────────────────────────
  {
    id: 28,
    infinitive: 'kommen',
    en: 'to come',
    es: 'venir',
    type: 'regular',
    stemChange: null,
    note: null,
    forms: {
      'ich':      { form: 'komme',   highlight: false },
      'du':       { form: 'kommst',  highlight: false },
      'er/sie/es':{ form: 'kommt',   highlight: false },
      'wir':      { form: 'kommen',  highlight: false },
      'ihr':      { form: 'kommt',   highlight: false },
      'sie/Sie':  { form: 'kommen',  highlight: false },
    },
  },
  {
    id: 29,
    infinitive: 'lernen',
    en: 'to learn / study',
    es: 'aprender / estudiar',
    type: 'regular',
    stemChange: null,
    note: null,
    forms: {
      'ich':      { form: 'lerne',   highlight: false },
      'du':       { form: 'lernst',  highlight: false },
      'er/sie/es':{ form: 'lernt',   highlight: false },
      'wir':      { form: 'lernen',  highlight: false },
      'ihr':      { form: 'lernt',   highlight: false },
      'sie/Sie':  { form: 'lernen',  highlight: false },
    },
  },
  {
    id: 30,
    infinitive: 'wohnen',
    en: 'to live / reside',
    es: 'vivir / residir',
    type: 'regular',
    stemChange: null,
    note: null,
    forms: {
      'ich':      { form: 'wohne',   highlight: false },
      'du':       { form: 'wohnst',  highlight: false },
      'er/sie/es':{ form: 'wohnt',   highlight: false },
      'wir':      { form: 'wohnen',  highlight: false },
      'ihr':      { form: 'wohnt',   highlight: false },
      'sie/Sie':  { form: 'wohnen',  highlight: false },
    },
  },
  {
    id: 31,
    infinitive: 'schreiben',
    en: 'to write',
    es: 'escribir',
    type: 'regular',
    stemChange: null,
    note: null,
    forms: {
      'ich':      { form: 'schreibe',   highlight: false },
      'du':       { form: 'schreibst',  highlight: false },
      'er/sie/es':{ form: 'schreibt',   highlight: false },
      'wir':      { form: 'schreiben',  highlight: false },
      'ihr':      { form: 'schreibt',   highlight: false },
      'sie/Sie':  { form: 'schreiben',  highlight: false },
    },
  },
];
