export const GERMAN_ADJECTIVE_CARDS = [
  { id: 1,  en: 'big',       es: 'grande',    de: 'groß',       emoji: '🔴' },
  { id: 2,  en: 'small',     es: 'pequeño',   de: 'klein',      emoji: '🔵' },
  { id: 3,  en: 'tall',      es: 'alto',      de: 'hoch',       emoji: '🏔️' },
  { id: 4,  en: 'short',     es: 'bajo/corto',de: 'kurz',       emoji: '📏' },
  { id: 5,  en: 'ugly',      es: 'feo',       de: 'hässlich',   emoji: '😤' },
  { id: 6,  en: 'beautiful', es: 'hermoso',   de: 'schön',      emoji: '🌸' },
  { id: 7,  en: 'fast',      es: 'rápido',    de: 'schnell',    emoji: '⚡' },
  { id: 8,  en: 'slow',      es: 'lento',     de: 'langsam',    emoji: '🐢' },
  { id: 9,  en: 'old',       es: 'viejo',     de: 'alt',        emoji: '👴' },
  { id: 10, en: 'young',     es: 'joven',     de: 'jung',       emoji: '🧒' },
  { id: 11, en: 'hot',       es: 'caliente',  de: 'heiß',       emoji: '🔥' },
  { id: 12, en: 'cold',      es: 'frío',      de: 'kalt',       emoji: '❄️' },
  { id: 13, en: 'good',      es: 'bueno',     de: 'gut',        emoji: '✅' },
  { id: 14, en: 'bad',       es: 'malo',      de: 'schlecht',   emoji: '❌' },
  { id: 15, en: 'happy',     es: 'feliz',     de: 'glücklich',  emoji: '😊' },
  { id: 16, en: 'sad',       es: 'triste',    de: 'traurig',    emoji: '😢' },
  { id: 17, en: 'strong',    es: 'fuerte',    de: 'stark',      emoji: '💪' },
  { id: 18, en: 'weak',      es: 'débil',     de: 'schwach',    emoji: '🍃' },
  { id: 19, en: 'new',       es: 'nuevo',     de: 'neu',        emoji: '✨' },
  { id: 20, en: 'long',      es: 'largo',     de: 'lang',       emoji: '📐' },
  { id: 21, en: 'loud',      es: 'ruidoso',   de: 'laut',       emoji: '📢' },
  { id: 22, en: 'quiet',     es: 'silencioso',de: 'leise',      emoji: '🤫' },
  { id: 23, en: 'heavy',     es: 'pesado',    de: 'schwer',     emoji: '🏋️' },
  { id: 24, en: 'light',     es: 'ligero',    de: 'leicht',     emoji: '🪶' },
];
