export const GERMAN_VOCABULARY_QUIZ = {
  en: [
    { id: 1, word: "Hallo", ipa: "[ˈhaloː]", question: "What does 'hallo' mean?", options: ["Hello", "Goodbye", "Thank you", "Please"], correctIndex: 0, reference: "Greeting" },
    { id: 2, word: "Auf Wiedersehen", ipa: "[ˌaʊf ˈviːdɐˌzeːən]", question: "What does 'auf Wiedersehen' mean?", options: ["Goodbye", "Good morning", "Good night", "See you"], correctIndex: 0, reference: "Farewell" },
    { id: 3, word: "Danke", ipa: "[ˈdaŋkə]", question: "What does 'danke' mean?", options: ["Thank you", "Please", "Sorry", "Yes"], correctIndex: 0, reference: "Courtesy" },
    { id: 4, word: "Bitte", ipa: "[ˈbɪtə]", question: "What does 'bitte' mean?", options: ["Please / You're welcome", "Thank you", "Excuse me", "No"], correctIndex: 0, reference: "Courtesy" },
    { id: 5, word: "Guten Morgen", ipa: "[ˈɡuːtən ˈmɔʁɡən]", question: "What does 'guten Morgen' mean?", options: ["Good morning", "Good afternoon", "Good evening", "Good night"], correctIndex: 0, reference: "Greeting" },
    { id: 6, word: "Gute Nacht", ipa: "[ˈɡuːtə naxt]", question: "What does 'gute Nacht' mean?", options: ["Good night", "Good morning", "Good evening", "Goodbye"], correctIndex: 0, reference: "Greeting" },
    { id: 7, word: "Ja", ipa: "[jaː]", question: "What does 'ja' mean?", options: ["Yes", "No", "Maybe", "Never"], correctIndex: 0, reference: "Basic" },
    { id: 8, word: "Nein", ipa: "[naɪn]", question: "What does 'nein' mean?", options: ["No", "Yes", "Never", "Nine"], correctIndex: 0, reference: "Basic" },
    { id: 9, word: "Entschuldigung", ipa: "[ɛntˈʃʊldɪɡʊŋ]", question: "What does 'Entschuldigung' mean?", options: ["Excuse me / Sorry", "Thank you", "Please", "Goodbye"], correctIndex: 0, reference: "Courtesy" },
    { id: 10, word: "Wasser", ipa: "[ˈvasɐ]", question: "What does 'Wasser' mean?", options: ["Water", "Fire", "Air", "Earth"], correctIndex: 0, reference: "Noun" },
    { id: 11, word: "Essen", ipa: "[ˈɛsən]", question: "What does 'Essen' mean?", options: ["Food / Eating", "Drinking", "Sleeping", "Running"], correctIndex: 0, reference: "Noun/Verb" },
    { id: 12, word: "Haus", ipa: "[haʊs]", question: "What does 'Haus' mean?", options: ["House", "Car", "School", "Street"], correctIndex: 0, reference: "Noun" },
    { id: 13, word: "Auto", ipa: "[ˈaʊtoː]", question: "What does 'Auto' mean?", options: ["Car", "Bus", "Train", "Bicycle"], correctIndex: 0, reference: "Noun" },
    { id: 14, word: "Zeit", ipa: "[tsaɪt]", question: "What does 'Zeit' mean?", options: ["Time", "Day", "Night", "Hour"], correctIndex: 0, reference: "Noun" },
    { id: 15, word: "Arbeit", ipa: "[ˈaʁbaɪt]", question: "What does 'Arbeit' mean?", options: ["Work", "Play", "Rest", "School"], correctIndex: 0, reference: "Noun" },
    { id: 16, word: "Freund", ipa: "[fʁɔɪnt]", question: "What does 'Freund' mean?", options: ["Friend", "Enemy", "Stranger", "Neighbor"], correctIndex: 0, reference: "Noun" },
    { id: 17, word: "Familie", ipa: "[faˈmiːliə]", question: "What does 'Familie' mean?", options: ["Family", "Friend", "Group", "Nation"], correctIndex: 0, reference: "Noun" },
    { id: 18, word: "Liebe", ipa: "[ˈliːbə]", question: "What does 'Liebe' mean?", options: ["Love", "Peace", "Joy", "Hope"], correctIndex: 0, reference: "Noun" },
    { id: 19, word: "Herz", ipa: "[hɛʁts]", question: "What does 'Herz' mean?", options: ["Heart", "Mind", "Soul", "Body"], correctIndex: 0, reference: "Noun" },
    { id: 20, word: "Leben", ipa: "[ˈleːbən]", question: "What does 'Leben' mean?", options: ["Life", "Death", "Birth", "Age"], correctIndex: 0, reference: "Noun" },
    { id: 21, word: "Wahrheit", ipa: "[ˈvaːʁhaɪt]", question: "What does 'Wahrheit' mean?", options: ["Truth", "Lie", "Secret", "Story"], correctIndex: 0, reference: "Noun" },
    { id: 22, word: "Friede", ipa: "[ˈfʁiːdə]", question: "What does 'Friede' mean?", options: ["Peace", "War", "Conflict", "Silence"], correctIndex: 0, reference: "Noun" },
    { id: 23, word: "Freiheit", ipa: "[ˈfʁaɪhaɪt]", question: "What does 'Freiheit' mean?", options: ["Freedom", "Justice", "Order", "Power"], correctIndex: 0, reference: "Noun" },
    { id: 24, word: "Freude", ipa: "[ˈfʁɔɪdə]", question: "What does 'Freude' mean?", options: ["Joy", "Sadness", "Anger", "Fear"], correctIndex: 0, reference: "Noun" },
    { id: 25, word: "Hoffnung", ipa: "[ˈhɔfnʊŋ]", question: "What does 'Hoffnung' mean?", options: ["Hope", "Fear", "Doubt", "Despair"], correctIndex: 0, reference: "Noun" },
    { id: 26, word: "Stärke", ipa: "[ˈʃtɛʁkə]", question: "What does 'Stärke' mean?", options: ["Strength", "Weakness", "Speed", "Wisdom"], correctIndex: 0, reference: "Noun" },
    { id: 27, word: "Weg", ipa: "[veːk]", question: "What does 'Weg' mean?", options: ["Way / Path", "Goal", "End", "Start"], correctIndex: 0, reference: "Noun" },
    { id: 28, word: "Welt", ipa: "[vɛlt]", question: "What does 'Welt' mean?", options: ["World", "Country", "City", "Village"], correctIndex: 0, reference: "Noun" },
    { id: 29, word: "Land", ipa: "[lant]", question: "What does 'Land' mean?", options: ["Land / Country", "Sea", "Sky", "Mountain"], correctIndex: 0, reference: "Noun" },
    { id: 30, word: "Stadt", ipa: "[ʃtat]", question: "What does 'Stadt' mean?", options: ["City", "Village", "Farm", "Forest"], correctIndex: 0, reference: "Noun" },
    { id: 31, word: "Sprache", ipa: "[ˈʃpʁaːxə]", question: "What does 'Sprache' mean?", options: ["Language", "Music", "Art", "Science"], correctIndex: 0, reference: "Noun" },
    { id: 32, word: "Schule", ipa: "[ˈʃuːlə]", question: "What does 'Schule' mean?", options: ["School", "Church", "Market", "Hospital"], correctIndex: 0, reference: "Noun" },
    { id: 33, word: "Buch", ipa: "[buːx]", question: "What does 'Buch' mean?", options: ["Book", "Pen", "Paper", "Letter"], correctIndex: 0, reference: "Noun" },
    { id: 34, word: "Geld", ipa: "[ɡɛlt]", question: "What does 'Geld' mean?", options: ["Money", "Gold", "Silver", "Trade"], correctIndex: 0, reference: "Noun" },
    { id: 35, word: "Kind", ipa: "[kɪnt]", question: "What does 'Kind' mean?", options: ["Child", "Adult", "Baby", "Youth"], correctIndex: 0, reference: "Noun" },
    { id: 36, word: "Mensch", ipa: "[mɛnʃ]", question: "What does 'Mensch' mean?", options: ["Human being / Person", "Animal", "Angel", "God"], correctIndex: 0, reference: "Noun" },
    { id: 37, word: "Sonne", ipa: "[ˈzɔnə]", question: "What does 'Sonne' mean?", options: ["Sun", "Moon", "Star", "Cloud"], correctIndex: 0, reference: "Noun" },
    { id: 38, word: "Natur", ipa: "[naˈtuːɐ̯]", question: "What does 'Natur' mean?", options: ["Nature", "Culture", "Art", "Science"], correctIndex: 0, reference: "Noun" },
    { id: 39, word: "Gott", ipa: "[ɡɔt]", question: "What does 'Gott' mean?", options: ["God", "Angel", "Heaven", "Spirit"], correctIndex: 0, reference: "Noun" },
    { id: 40, word: "Tschüss", ipa: "[tʃʏs]", question: "What does 'Tschüss' mean?", options: ["Bye / See you", "Hello", "Thank you", "Please"], correctIndex: 0, reference: "Farewell" }
  ],
  es: [
    { id: 1, word: "Hallo", ipa: "[ˈhaloː]", question: "¿Qué significa 'hallo'?", options: ["Hola", "Adiós", "Gracias", "Por favor"], correctIndex: 0, reference: "Saludo" },
    { id: 2, word: "Auf Wiedersehen", ipa: "[ˌaʊf ˈviːdɐˌzeːən]", question: "¿Qué significa 'auf Wiedersehen'?", options: ["Adiós", "Buenos días", "Buenas noches", "Hasta luego"], correctIndex: 0, reference: "Despedida" },
    { id: 3, word: "Danke", ipa: "[ˈdaŋkə]", question: "¿Qué significa 'danke'?", options: ["Gracias", "Por favor", "Lo siento", "Sí"], correctIndex: 0, reference: "Cortesía" },
    { id: 4, word: "Bitte", ipa: "[ˈbɪtə]", question: "¿Qué significa 'bitte'?", options: ["Por favor / De nada", "Gracias", "Perdón", "No"], correctIndex: 0, reference: "Cortesía" },
    { id: 5, word: "Guten Morgen", ipa: "[ˈɡuːtən ˈmɔʁɡən]", question: "¿Qué significa 'guten Morgen'?", options: ["Buenos días", "Buenas tardes", "Buenas noches", "Hasta luego"], correctIndex: 0, reference: "Saludo" },
    { id: 6, word: "Gute Nacht", ipa: "[ˈɡuːtə naxt]", question: "¿Qué significa 'gute Nacht'?", options: ["Buenas noches", "Buenos días", "Buenas tardes", "Adiós"], correctIndex: 0, reference: "Saludo" },
    { id: 7, word: "Ja", ipa: "[jaː]", question: "¿Qué significa 'ja'?", options: ["Sí", "No", "Quizás", "Nunca"], correctIndex: 0, reference: "Básico" },
    { id: 8, word: "Nein", ipa: "[naɪn]", question: "¿Qué significa 'nein'?", options: ["No", "Sí", "Nunca", "Nueve"], correctIndex: 0, reference: "Básico" },
    { id: 9, word: "Entschuldigung", ipa: "[ɛntˈʃʊldɪɡʊŋ]", question: "¿Qué significa 'Entschuldigung'?", options: ["Perdón / Disculpe", "Gracias", "Por favor", "Adiós"], correctIndex: 0, reference: "Cortesía" },
    { id: 10, word: "Wasser", ipa: "[ˈvasɐ]", question: "¿Qué significa 'Wasser'?", options: ["Agua", "Fuego", "Aire", "Tierra"], correctIndex: 0, reference: "Sustantivo" },
    { id: 11, word: "Essen", ipa: "[ˈɛsən]", question: "¿Qué significa 'Essen'?", options: ["Comida / Comer", "Beber", "Dormir", "Correr"], correctIndex: 0, reference: "Sustantivo/Verbo" },
    { id: 12, word: "Haus", ipa: "[haʊs]", question: "¿Qué significa 'Haus'?", options: ["Casa", "Auto", "Escuela", "Calle"], correctIndex: 0, reference: "Sustantivo" },
    { id: 13, word: "Auto", ipa: "[ˈaʊtoː]", question: "¿Qué significa 'Auto'?", options: ["Auto / Carro", "Autobús", "Tren", "Bicicleta"], correctIndex: 0, reference: "Sustantivo" },
    { id: 14, word: "Zeit", ipa: "[tsaɪt]", question: "¿Qué significa 'Zeit'?", options: ["Tiempo", "Día", "Noche", "Hora"], correctIndex: 0, reference: "Sustantivo" },
    { id: 15, word: "Arbeit", ipa: "[ˈaʁbaɪt]", question: "¿Qué significa 'Arbeit'?", options: ["Trabajo", "Juego", "Descanso", "Escuela"], correctIndex: 0, reference: "Sustantivo" },
    { id: 16, word: "Freund", ipa: "[fʁɔɪnt]", question: "¿Qué significa 'Freund'?", options: ["Amigo", "Enemigo", "Extraño", "Vecino"], correctIndex: 0, reference: "Sustantivo" },
    { id: 17, word: "Familie", ipa: "[faˈmiːliə]", question: "¿Qué significa 'Familie'?", options: ["Familia", "Amigo", "Grupo", "Nación"], correctIndex: 0, reference: "Sustantivo" },
    { id: 18, word: "Liebe", ipa: "[ˈliːbə]", question: "¿Qué significa 'Liebe'?", options: ["Amor", "Paz", "Alegría", "Esperanza"], correctIndex: 0, reference: "Sustantivo" },
    { id: 19, word: "Herz", ipa: "[hɛʁts]", question: "¿Qué significa 'Herz'?", options: ["Corazón", "Mente", "Alma", "Cuerpo"], correctIndex: 0, reference: "Sustantivo" },
    { id: 20, word: "Leben", ipa: "[ˈleːbən]", question: "¿Qué significa 'Leben'?", options: ["Vida", "Muerte", "Nacimiento", "Edad"], correctIndex: 0, reference: "Sustantivo" },
    { id: 21, word: "Wahrheit", ipa: "[ˈvaːʁhaɪt]", question: "¿Qué significa 'Wahrheit'?", options: ["Verdad", "Mentira", "Secreto", "Historia"], correctIndex: 0, reference: "Sustantivo" },
    { id: 22, word: "Friede", ipa: "[ˈfʁiːdə]", question: "¿Qué significa 'Friede'?", options: ["Paz", "Guerra", "Conflicto", "Silencio"], correctIndex: 0, reference: "Sustantivo" },
    { id: 23, word: "Freiheit", ipa: "[ˈfʁaɪhaɪt]", question: "¿Qué significa 'Freiheit'?", options: ["Libertad", "Justicia", "Orden", "Poder"], correctIndex: 0, reference: "Sustantivo" },
    { id: 24, word: "Freude", ipa: "[ˈfʁɔɪdə]", question: "¿Qué significa 'Freude'?", options: ["Alegría", "Tristeza", "Enojo", "Miedo"], correctIndex: 0, reference: "Sustantivo" },
    { id: 25, word: "Hoffnung", ipa: "[ˈhɔfnʊŋ]", question: "¿Qué significa 'Hoffnung'?", options: ["Esperanza", "Miedo", "Duda", "Desesperación"], correctIndex: 0, reference: "Sustantivo" },
    { id: 26, word: "Stärke", ipa: "[ˈʃtɛʁkə]", question: "¿Qué significa 'Stärke'?", options: ["Fuerza", "Debilidad", "Velocidad", "Sabiduría"], correctIndex: 0, reference: "Sustantivo" },
    { id: 27, word: "Weg", ipa: "[veːk]", question: "¿Qué significa 'Weg'?", options: ["Camino / Vía", "Meta", "Fin", "Inicio"], correctIndex: 0, reference: "Sustantivo" },
    { id: 28, word: "Welt", ipa: "[vɛlt]", question: "¿Qué significa 'Welt'?", options: ["Mundo", "País", "Ciudad", "Pueblo"], correctIndex: 0, reference: "Sustantivo" },
    { id: 29, word: "Land", ipa: "[lant]", question: "¿Qué significa 'Land'?", options: ["Tierra / País", "Mar", "Cielo", "Montaña"], correctIndex: 0, reference: "Sustantivo" },
    { id: 30, word: "Stadt", ipa: "[ʃtat]", question: "¿Qué significa 'Stadt'?", options: ["Ciudad", "Pueblo", "Granja", "Bosque"], correctIndex: 0, reference: "Sustantivo" },
    { id: 31, word: "Sprache", ipa: "[ˈʃpʁaːxə]", question: "¿Qué significa 'Sprache'?", options: ["Idioma / Lengua", "Música", "Arte", "Ciencia"], correctIndex: 0, reference: "Sustantivo" },
    { id: 32, word: "Schule", ipa: "[ˈʃuːlə]", question: "¿Qué significa 'Schule'?", options: ["Escuela", "Iglesia", "Mercado", "Hospital"], correctIndex: 0, reference: "Sustantivo" },
    { id: 33, word: "Buch", ipa: "[buːx]", question: "¿Qué significa 'Buch'?", options: ["Libro", "Pluma", "Papel", "Carta"], correctIndex: 0, reference: "Sustantivo" },
    { id: 34, word: "Geld", ipa: "[ɡɛlt]", question: "¿Qué significa 'Geld'?", options: ["Dinero", "Oro", "Plata", "Comercio"], correctIndex: 0, reference: "Sustantivo" },
    { id: 35, word: "Kind", ipa: "[kɪnt]", question: "¿Qué significa 'Kind'?", options: ["Niño", "Adulto", "Bebé", "Joven"], correctIndex: 0, reference: "Sustantivo" },
    { id: 36, word: "Mensch", ipa: "[mɛnʃ]", question: "¿Qué significa 'Mensch'?", options: ["Ser humano / Persona", "Animal", "Ángel", "Dios"], correctIndex: 0, reference: "Sustantivo" },
    { id: 37, word: "Sonne", ipa: "[ˈzɔnə]", question: "¿Qué significa 'Sonne'?", options: ["Sol", "Luna", "Estrella", "Nube"], correctIndex: 0, reference: "Sustantivo" },
    { id: 38, word: "Natur", ipa: "[naˈtuːɐ̯]", question: "¿Qué significa 'Natur'?", options: ["Naturaleza", "Cultura", "Arte", "Ciencia"], correctIndex: 0, reference: "Sustantivo" },
    { id: 39, word: "Gott", ipa: "[ɡɔt]", question: "¿Qué significa 'Gott'?", options: ["Dios", "Ángel", "Cielo", "Espíritu"], correctIndex: 0, reference: "Sustantivo" },
    { id: 40, word: "Tschüss", ipa: "[tʃʏs]", question: "¿Qué significa 'Tschüss'?", options: ["Chao / Hasta luego", "Hola", "Gracias", "Por favor"], correctIndex: 0, reference: "Despedida" }
  ]
};
