// Top 500 everyday German words.
//
// Stored as a compact table rather than 1000 hand-written card objects (500 words
// x 2 languages). buildDeck() expands it into the same card shape the other decks
// use, so FlashCards renders it unchanged.
//
// Row: [word, IPA, English, Spanish, category]
// Nouns carry their article — the gender is half of what you need to learn.
//
// Distractors are drawn from the SAME category, deterministically (the next
// distinct translations in the group). Same-category options make the quiz
// actually test the word instead of being guessable by topic, and determinism
// keeps the deck stable between reloads.

const CATEGORY_LABEL = {
  people:   { en: 'People & family',   es: 'Personas y familia' },
  food:     { en: 'Food & drink',      es: 'Comida y bebida' },
  home:     { en: 'House & furniture', es: 'Casa y muebles' },
  clothes:  { en: 'Clothing',          es: 'Ropa' },
  body:     { en: 'Body & health',     es: 'Cuerpo y salud' },
  time:     { en: 'Time & calendar',   es: 'Tiempo y calendario' },
  travel:   { en: 'Travel & transport',es: 'Viajes y transporte' },
  work:     { en: 'Work & school',     es: 'Trabajo y escuela' },
  city:     { en: 'City & places',     es: 'Ciudad y lugares' },
  nature:   { en: 'Nature & weather',  es: 'Naturaleza y clima' },
  verb:     { en: 'Common verbs',      es: 'Verbos comunes' },
  adj:      { en: 'Common adjectives', es: 'Adjetivos comunes' },
  fn:       { en: 'Function words',    es: 'Palabras funcionales' },
};

const W = [
  // ── People & family (35) ──
  ['der Mann', '[man]', 'man', 'hombre', 'people'],
  ['die Frau', '[fʁaʊ]', 'woman', 'mujer', 'people'],
  ['das Kind', '[kɪnt]', 'child', 'niño', 'people'],
  ['der Junge', '[ˈjʊŋə]', 'boy', 'chico', 'people'],
  ['das Mädchen', '[ˈmɛːtçən]', 'girl', 'chica', 'people'],
  ['der Vater', '[ˈfaːtɐ]', 'father', 'padre', 'people'],
  ['die Mutter', '[ˈmʊtɐ]', 'mother', 'madre', 'people'],
  ['die Eltern', '[ˈɛltɐn]', 'parents', 'padres', 'people'],
  ['der Sohn', '[zoːn]', 'son', 'hijo', 'people'],
  ['die Tochter', '[ˈtɔxtɐ]', 'daughter', 'hija', 'people'],
  ['der Bruder', '[ˈbʁuːdɐ]', 'brother', 'hermano', 'people'],
  ['die Schwester', '[ˈʃvɛstɐ]', 'sister', 'hermana', 'people'],
  ['die Familie', '[faˈmiːliə]', 'family', 'familia', 'people'],
  ['der Freund', '[fʁɔɪnt]', 'friend (male)', 'amigo', 'people'],
  ['die Freundin', '[ˈfʁɔɪndɪn]', 'friend (female)', 'amiga', 'people'],
  ['der Nachbar', '[ˈnaːxbaːɐ̯]', 'neighbour', 'vecino', 'people'],
  ['der Mensch', '[mɛnʃ]', 'human being', 'ser humano', 'people'],
  ['die Leute', '[ˈlɔɪtə]', 'people', 'gente', 'people'],
  ['der Herr', '[hɛɐ̯]', 'gentleman / Mr', 'señor', 'people'],
  ['die Dame', '[ˈdaːmə]', 'lady', 'dama', 'people'],
  ['das Baby', '[ˈbeːbi]', 'baby', 'bebé', 'people'],
  ['der Opa', '[ˈoːpa]', 'grandpa (informal)', 'abuelito (coloquial)', 'people'],
  ['die Oma', '[ˈoːma]', 'grandma (informal)', 'abuelita (coloquial)', 'people'],
  ['der Großvater', '[ˈɡʁoːsˌfaːtɐ]', 'grandfather', 'abuelo', 'people'],
  ['die Großmutter', '[ˈɡʁoːsˌmʊtɐ]', 'grandmother', 'abuela', 'people'],
  ['der Onkel', '[ˈɔŋkəl]', 'uncle', 'tío', 'people'],
  ['die Tante', '[ˈtantə]', 'aunt', 'tía', 'people'],
  ['der Cousin', '[kuˈzɛ̃ː]', 'cousin (male)', 'primo', 'people'],
  ['die Cousine', '[kuˈziːnə]', 'cousin (female)', 'prima', 'people'],
  ['der Ehemann', '[ˈeːəˌman]', 'husband', 'esposo', 'people'],
  ['die Ehefrau', '[ˈeːəˌfʁaʊ]', 'wife', 'esposa', 'people'],
  ['das Paar', '[paːɐ̯]', 'couple', 'pareja', 'people'],
  ['der Gast', '[ɡast]', 'guest', 'invitado', 'people'],
  ['der Chef', '[ʃɛf]', 'boss', 'jefe', 'people'],
  ['die Person', '[pɛʁˈzoːn]', 'person', 'persona', 'people'],

  // ── Food & drink (55) ──
  ['das Essen', '[ˈɛsən]', 'food', 'comida', 'food'],
  ['das Getränk', '[ɡəˈtʁɛŋk]', 'drink', 'bebida', 'food'],
  ['das Wasser', '[ˈvasɐ]', 'water', 'agua', 'food'],
  ['das Brot', '[bʁoːt]', 'bread', 'pan', 'food'],
  ['die Butter', '[ˈbʊtɐ]', 'butter', 'mantequilla', 'food'],
  ['der Käse', '[ˈkɛːzə]', 'cheese', 'queso', 'food'],
  ['die Milch', '[mɪlç]', 'milk', 'leche', 'food'],
  ['das Ei', '[aɪ]', 'egg', 'huevo', 'food'],
  ['das Fleisch', '[flaɪʃ]', 'meat', 'carne', 'food'],
  ['der Fisch', '[fɪʃ]', 'fish', 'pescado', 'food'],
  ['das Gemüse', '[ɡəˈmyːzə]', 'vegetables', 'verduras', 'food'],
  ['das Obst', '[oːpst]', 'fruit', 'fruta', 'food'],
  ['der Apfel', '[ˈapfəl]', 'apple', 'manzana', 'food'],
  ['die Banane', '[baˈnaːnə]', 'banana', 'plátano', 'food'],
  ['die Orange', '[oˈʁãːʒə]', 'orange', 'naranja', 'food'],
  ['die Kartoffel', '[kaʁˈtɔfəl]', 'potato', 'papa', 'food'],
  ['die Tomate', '[toˈmaːtə]', 'tomato', 'jitomate', 'food'],
  ['der Salat', '[zaˈlaːt]', 'salad', 'ensalada', 'food'],
  ['die Zwiebel', '[ˈtsviːbəl]', 'onion', 'cebolla', 'food'],
  ['der Reis', '[ʁaɪs]', 'rice', 'arroz', 'food'],
  ['die Nudeln', '[ˈnuːdəln]', 'pasta / noodles', 'pasta', 'food'],
  ['die Suppe', '[ˈzʊpə]', 'soup', 'sopa', 'food'],
  ['der Zucker', '[ˈtsʊkɐ]', 'sugar', 'azúcar', 'food'],
  ['das Salz', '[zalts]', 'salt', 'sal', 'food'],
  ['der Pfeffer', '[ˈpfɛfɐ]', 'pepper', 'pimienta', 'food'],
  ['das Öl', '[øːl]', 'oil', 'aceite', 'food'],
  ['der Kaffee', '[ˈkafeː]', 'coffee', 'café', 'food'],
  ['der Tee', '[teː]', 'tea', 'té', 'food'],
  ['der Saft', '[zaft]', 'juice', 'jugo', 'food'],
  ['das Bier', '[biːɐ̯]', 'beer', 'cerveza', 'food'],
  ['der Wein', '[vaɪn]', 'wine', 'vino', 'food'],
  ['der Kuchen', '[ˈkuːxən]', 'cake', 'pastel', 'food'],
  ['die Schokolade', '[ʃokoˈlaːdə]', 'chocolate', 'chocolate', 'food'],
  ['das Eis', '[aɪs]', 'ice cream', 'helado', 'food'],
  ['das Frühstück', '[ˈfʁyːʃtʏk]', 'breakfast', 'desayuno', 'food'],
  ['das Mittagessen', '[ˈmɪtaːkˌʔɛsən]', 'lunch', 'almuerzo', 'food'],
  ['das Abendessen', '[ˈaːbəntˌʔɛsən]', 'dinner', 'cena', 'food'],
  ['der Hunger', '[ˈhʊŋɐ]', 'hunger', 'hambre', 'food'],
  ['der Durst', '[dʊʁst]', 'thirst', 'sed', 'food'],
  ['der Teller', '[ˈtɛlɐ]', 'plate', 'plato', 'food'],
  ['das Glas', '[ɡlaːs]', 'glass', 'vaso', 'food'],
  ['die Tasse', '[ˈtasə]', 'cup', 'taza', 'food'],
  ['die Gabel', '[ˈɡaːbəl]', 'fork', 'tenedor', 'food'],
  ['das Messer', '[ˈmɛsɐ]', 'knife', 'cuchillo', 'food'],
  ['der Löffel', '[ˈlœfəl]', 'spoon', 'cuchara', 'food'],
  ['die Flasche', '[ˈflaʃə]', 'bottle', 'botella', 'food'],
  ['das Restaurant', '[ʁɛstoˈʁãː]', 'restaurant', 'restaurante', 'food'],
  ['die Speisekarte', '[ˈʃpaɪzəˌkaʁtə]', 'menu', 'menú', 'food'],
  ['die Rechnung', '[ˈʁɛçnʊŋ]', 'bill', 'cuenta', 'food'],
  ['das Brötchen', '[ˈbʁøːtçən]', 'bread roll', 'panecillo', 'food'],
  ['die Wurst', '[vʊʁst]', 'sausage', 'salchicha', 'food'],
  ['der Joghurt', '[ˈjoːɡʊʁt]', 'yoghurt', 'yogur', 'food'],
  ['die Sahne', '[ˈzaːnə]', 'cream', 'crema', 'food'],
  ['der Honig', '[ˈhoːnɪç]', 'honey', 'miel', 'food'],
  ['die Marmelade', '[maʁməˈlaːdə]', 'jam', 'mermelada', 'food'],

  // ── House & furniture (40) ──
  ['das Haus', '[haʊs]', 'house', 'casa', 'home'],
  ['die Wohnung', '[ˈvoːnʊŋ]', 'apartment', 'departamento', 'home'],
  ['das Zimmer', '[ˈtsɪmɐ]', 'room', 'habitación', 'home'],
  ['die Küche', '[ˈkʏçə]', 'kitchen', 'cocina', 'home'],
  ['das Bad', '[baːt]', 'bathroom', 'baño', 'home'],
  ['das Schlafzimmer', '[ˈʃlaːfˌtsɪmɐ]', 'bedroom', 'recámara', 'home'],
  ['das Wohnzimmer', '[ˈvoːnˌtsɪmɐ]', 'living room', 'sala', 'home'],
  ['die Tür', '[tyːɐ̯]', 'door', 'puerta', 'home'],
  ['das Fenster', '[ˈfɛnstɐ]', 'window', 'ventana', 'home'],
  ['der Tisch', '[tɪʃ]', 'table', 'mesa', 'home'],
  ['der Stuhl', '[ʃtuːl]', 'chair', 'silla', 'home'],
  ['das Bett', '[bɛt]', 'bed', 'cama', 'home'],
  ['der Schrank', '[ʃʁaŋk]', 'cupboard / wardrobe', 'armario', 'home'],
  ['das Sofa', '[ˈzoːfa]', 'sofa', 'sofá', 'home'],
  ['der Boden', '[ˈboːdən]', 'floor', 'suelo', 'home'],
  ['die Wand', '[vant]', 'wall', 'pared', 'home'],
  ['das Dach', '[dax]', 'roof', 'techo', 'home'],
  ['die Treppe', '[ˈtʁɛpə]', 'stairs', 'escalera', 'home'],
  ['der Garten', '[ˈɡaʁtən]', 'garden', 'jardín', 'home'],
  ['der Schlüssel', '[ˈʃlʏsəl]', 'key', 'llave', 'home'],
  ['die Lampe', '[ˈlampə]', 'lamp', 'lámpara', 'home'],
  ['das Licht', '[lɪçt]', 'light', 'luz', 'home'],
  ['der Spiegel', '[ˈʃpiːɡəl]', 'mirror', 'espejo', 'home'],
  ['das Regal', '[ʁeˈɡaːl]', 'shelf', 'estante', 'home'],
  ['der Teppich', '[ˈtɛpɪç]', 'carpet', 'alfombra', 'home'],
  ['der Kühlschrank', '[ˈkyːlˌʃʁaŋk]', 'fridge', 'refrigerador', 'home'],
  ['der Herd', '[heːɐ̯t]', 'stove', 'estufa', 'home'],
  ['die Dusche', '[ˈduːʃə]', 'shower', 'regadera', 'home'],
  ['die Toilette', '[toaˈlɛtə]', 'toilet', 'inodoro', 'home'],
  ['das Handtuch', '[ˈhantˌtuːx]', 'towel', 'toalla', 'home'],
  ['die Seife', '[ˈzaɪfə]', 'soap', 'jabón', 'home'],
  ['der Müll', '[mʏl]', 'rubbish', 'basura', 'home'],
  ['die Miete', '[ˈmiːtə]', 'rent', 'renta', 'home'],
  ['der Balkon', '[balˈkoːn]', 'balcony', 'balcón', 'home'],
  ['der Keller', '[ˈkɛlɐ]', 'cellar', 'sótano', 'home'],
  ['die Decke', '[ˈdɛkə]', 'blanket', 'cobija', 'home'],
  ['das Kissen', '[ˈkɪsən]', 'pillow', 'almohada', 'home'],
  ['der Ofen', '[ˈoːfən]', 'oven', 'horno', 'home'],
  ['die Uhr', '[uːɐ̯]', 'clock', 'reloj', 'home'],
  ['der Schreibtisch', '[ˈʃʁaɪpˌtɪʃ]', 'desk', 'escritorio', 'home'],

  // ── Clothing (25) ──
  ['die Kleidung', '[ˈklaɪdʊŋ]', 'clothing', 'ropa', 'clothes'],
  ['das Hemd', '[hɛmt]', 'shirt', 'camisa', 'clothes'],
  ['die Hose', '[ˈhoːzə]', 'trousers', 'pantalón', 'clothes'],
  ['der Rock', '[ʁɔk]', 'skirt', 'falda', 'clothes'],
  ['das Kleid', '[klaɪt]', 'dress', 'vestido', 'clothes'],
  ['die Jacke', '[ˈjakə]', 'jacket', 'chamarra', 'clothes'],
  ['der Mantel', '[ˈmantəl]', 'coat', 'abrigo', 'clothes'],
  ['der Pullover', '[pʊˈloːvɐ]', 'sweater', 'suéter', 'clothes'],
  ['das T-Shirt', '[ˈtiːʃœʁt]', 't-shirt', 'playera', 'clothes'],
  ['die Schuhe', '[ˈʃuːə]', 'shoes', 'zapatos', 'clothes'],
  ['die Socken', '[ˈzɔkən]', 'socks', 'calcetines', 'clothes'],
  ['der Hut', '[huːt]', 'hat', 'sombrero', 'clothes'],
  ['die Mütze', '[ˈmʏtsə]', 'cap', 'gorro', 'clothes'],
  ['der Schal', '[ʃaːl]', 'scarf', 'bufanda', 'clothes'],
  ['die Handschuhe', '[ˈhantˌʃuːə]', 'gloves', 'guantes', 'clothes'],
  ['der Gürtel', '[ˈɡʏʁtəl]', 'belt', 'cinturón', 'clothes'],
  ['die Tasche', '[ˈtaʃə]', 'bag', 'bolsa', 'clothes'],
  ['die Brille', '[ˈbʁɪlə]', 'glasses', 'lentes', 'clothes'],
  ['der Ring', '[ʁɪŋ]', 'ring', 'anillo', 'clothes'],
  ['die Größe', '[ˈɡʁøːsə]', 'size', 'talla', 'clothes'],
  ['die Farbe', '[ˈfaʁbə]', 'colour', 'color', 'clothes'],
  ['der Anzug', '[ˈantsuːk]', 'suit', 'traje', 'clothes'],
  ['die Bluse', '[ˈbluːzə]', 'blouse', 'blusa', 'clothes'],
  ['der Regenschirm', '[ˈʁeːɡənˌʃɪʁm]', 'umbrella', 'paraguas', 'clothes'],
  ['die Jeans', '[dʒiːns]', 'jeans', 'pantalón de mezclilla', 'clothes'],

  // ── Body & health (35) ──
  ['der Körper', '[ˈkœʁpɐ]', 'body', 'cuerpo', 'body'],
  ['der Kopf', '[kɔpf]', 'head', 'cabeza', 'body'],
  ['das Gesicht', '[ɡəˈzɪçt]', 'face', 'cara', 'body'],
  ['das Auge', '[ˈaʊɡə]', 'eye', 'ojo', 'body'],
  ['das Ohr', '[oːɐ̯]', 'ear', 'oreja', 'body'],
  ['die Nase', '[ˈnaːzə]', 'nose', 'nariz', 'body'],
  ['der Mund', '[mʊnt]', 'mouth', 'boca', 'body'],
  ['der Zahn', '[tsaːn]', 'tooth', 'diente', 'body'],
  ['das Haar', '[haːɐ̯]', 'hair', 'cabello', 'body'],
  ['der Hals', '[hals]', 'neck / throat', 'cuello', 'body'],
  ['die Hand', '[hant]', 'hand', 'mano', 'body'],
  ['der Arm', '[aʁm]', 'arm', 'brazo', 'body'],
  ['der Finger', '[ˈfɪŋɐ]', 'finger', 'dedo', 'body'],
  ['das Bein', '[baɪn]', 'leg', 'pierna', 'body'],
  ['der Fuß', '[fuːs]', 'foot', 'pie', 'body'],
  ['der Rücken', '[ˈʁʏkən]', 'back', 'espalda', 'body'],
  ['der Bauch', '[baʊx]', 'belly', 'vientre', 'body'],
  ['das Herz', '[hɛʁts]', 'heart', 'corazón', 'body'],
  ['das Blut', '[bluːt]', 'blood', 'sangre', 'body'],
  ['die Haut', '[haʊt]', 'skin', 'piel', 'body'],
  ['der Arzt', '[aːɐ̯tst]', 'doctor (male)', 'médico', 'body'],
  ['die Ärztin', '[ˈɛːɐ̯tstɪn]', 'doctor (female)', 'médica', 'body'],
  ['das Krankenhaus', '[ˈkʁaŋkənˌhaʊs]', 'hospital', 'hospital', 'body'],
  ['die Apotheke', '[apoˈteːkə]', 'pharmacy', 'farmacia', 'body'],
  ['die Medizin', '[mediˈtsiːn]', 'medicine', 'medicina', 'body'],
  ['die Krankheit', '[ˈkʁaŋkhaɪt]', 'illness', 'enfermedad', 'body'],
  ['die Schmerzen', '[ˈʃmɛʁtsən]', 'pain', 'dolor', 'body'],
  ['das Fieber', '[ˈfiːbɐ]', 'fever', 'fiebre', 'body'],
  ['die Erkältung', '[ɛɐ̯ˈkɛltʊŋ]', 'a cold', 'resfriado', 'body'],
  ['der Husten', '[ˈhuːstən]', 'cough', 'tos', 'body'],
  ['die Gesundheit', '[ɡəˈzʊnthaɪt]', 'health', 'salud', 'body'],
  ['der Termin', '[tɛʁˈmiːn]', 'appointment', 'cita', 'body'],
  ['die Praxis', '[ˈpʁaksɪs]', "doctor's office", 'consultorio', 'body'],
  ['das Rezept', '[ʁeˈtsɛpt]', 'prescription', 'receta', 'body'],
  ['die Tablette', '[taˈblɛtə]', 'tablet / pill', 'pastilla', 'body'],

  // ── Time & calendar (35) ──
  ['die Zeit', '[tsaɪt]', 'time', 'tiempo', 'time'],
  ['der Tag', '[taːk]', 'day', 'día', 'time'],
  ['die Woche', '[ˈvɔxə]', 'week', 'semana', 'time'],
  ['der Monat', '[ˈmoːnat]', 'month', 'mes', 'time'],
  ['das Jahr', '[jaːɐ̯]', 'year', 'año', 'time'],
  ['die Stunde', '[ˈʃtʊndə]', 'hour', 'hora', 'time'],
  ['die Minute', '[miˈnuːtə]', 'minute', 'minuto', 'time'],
  ['die Sekunde', '[zeˈkʊndə]', 'second', 'segundo', 'time'],
  ['der Morgen', '[ˈmɔʁɡən]', 'morning', 'la mañana', 'time'],
  ['der Mittag', '[ˈmɪtaːk]', 'midday', 'mediodía', 'time'],
  ['der Abend', '[ˈaːbənt]', 'evening', 'la tarde-noche', 'time'],
  ['die Nacht', '[naxt]', 'night', 'noche', 'time'],
  ['heute', '[ˈhɔɪtə]', 'today', 'hoy', 'time'],
  ['morgen', '[ˈmɔʁɡən]', 'tomorrow', 'mañana', 'time'],
  ['gestern', '[ˈɡɛstɐn]', 'yesterday', 'ayer', 'time'],
  ['jetzt', '[jɛtst]', 'now', 'ahora', 'time'],
  ['später', '[ˈʃpɛːtɐ]', 'later', 'más tarde', 'time'],
  ['früh', '[fʁyː]', 'early', 'temprano', 'time'],
  ['spät', '[ʃpɛːt]', 'late', 'tarde', 'time'],
  ['immer', '[ˈɪmɐ]', 'always', 'siempre', 'time'],
  ['nie', '[niː]', 'never', 'nunca', 'time'],
  ['oft', '[ɔft]', 'often', 'a menudo', 'time'],
  ['manchmal', '[ˈmançmaːl]', 'sometimes', 'a veces', 'time'],
  ['der Montag', '[ˈmoːntaːk]', 'Monday', 'lunes', 'time'],
  ['der Dienstag', '[ˈdiːnstaːk]', 'Tuesday', 'martes', 'time'],
  ['der Mittwoch', '[ˈmɪtvɔx]', 'Wednesday', 'miércoles', 'time'],
  ['der Donnerstag', '[ˈdɔnɐstaːk]', 'Thursday', 'jueves', 'time'],
  ['der Freitag', '[ˈfʁaɪtaːk]', 'Friday', 'viernes', 'time'],
  ['der Samstag', '[ˈzamstaːk]', 'Saturday', 'sábado', 'time'],
  ['der Sonntag', '[ˈzɔntaːk]', 'Sunday', 'domingo', 'time'],
  ['das Wochenende', '[ˈvɔxənˌʔɛndə]', 'weekend', 'fin de semana', 'time'],
  ['der Sommer', '[ˈzɔmɐ]', 'summer', 'verano', 'time'],
  ['der Winter', '[ˈvɪntɐ]', 'winter', 'invierno', 'time'],
  ['der Frühling', '[ˈfʁyːlɪŋ]', 'spring', 'primavera', 'time'],
  ['der Herbst', '[hɛʁpst]', 'autumn', 'otoño', 'time'],

  // ── Travel & transport (35) ──
  ['die Reise', '[ˈʁaɪzə]', 'trip', 'viaje', 'travel'],
  ['das Auto', '[ˈaʊtoː]', 'car', 'coche', 'travel'],
  ['der Bus', '[bʊs]', 'bus', 'autobús', 'travel'],
  ['der Zug', '[tsuːk]', 'train', 'tren', 'travel'],
  ['das Fahrrad', '[ˈfaːɐ̯ˌʁaːt]', 'bicycle', 'bicicleta', 'travel'],
  ['das Flugzeug', '[ˈfluːkˌtsɔɪk]', 'airplane', 'avión', 'travel'],
  ['das Schiff', '[ʃɪf]', 'ship', 'barco', 'travel'],
  ['die Bahn', '[baːn]', 'railway', 'ferrocarril', 'travel'],
  ['der Bahnhof', '[ˈbaːnˌhoːf]', 'train station', 'estación de tren', 'travel'],
  ['der Flughafen', '[ˈfluːkˌhaːfən]', 'airport', 'aeropuerto', 'travel'],
  ['die Haltestelle', '[ˈhaltəˌʃtɛlə]', 'stop', 'parada', 'travel'],
  ['die Fahrkarte', '[ˈfaːɐ̯ˌkaʁtə]', 'ticket', 'boleto', 'travel'],
  ['der Fahrplan', '[ˈfaːɐ̯ˌplaːn]', 'timetable', 'horario', 'travel'],
  ['die Straße', '[ˈʃtʁaːsə]', 'street', 'calle', 'travel'],
  ['der Weg', '[veːk]', 'way / path', 'camino', 'travel'],
  ['die Ampel', '[ˈampəl]', 'traffic light', 'semáforo', 'travel'],
  ['das Gepäck', '[ɡəˈpɛk]', 'luggage', 'equipaje', 'travel'],
  ['der Koffer', '[ˈkɔfɐ]', 'suitcase', 'maleta', 'travel'],
  ['der Pass', '[pas]', 'passport', 'pasaporte', 'travel'],
  ['die Grenze', '[ˈɡʁɛntsə]', 'border', 'frontera', 'travel'],
  ['das Hotel', '[hoˈtɛl]', 'hotel', 'hotel', 'travel'],
  ['der Urlaub', '[ˈuːɐ̯laʊp]', 'holiday', 'vacaciones', 'travel'],
  ['die Karte', '[ˈkaʁtə]', 'map', 'mapa', 'travel'],
  ['die Richtung', '[ˈʁɪçtʊŋ]', 'direction', 'sentido', 'travel'],
  ['links', '[lɪŋks]', 'left', 'a la izquierda', 'travel'],
  ['rechts', '[ʁɛçts]', 'right', 'a la derecha', 'travel'],
  ['geradeaus', '[ɡəʁaːdəˈʔaʊs]', 'straight ahead', 'todo derecho', 'travel'],
  ['die Abfahrt', '[ˈapˌfaːɐ̯t]', 'departure', 'partida', 'travel'],
  ['die Ankunft', '[ˈanˌkʊnft]', 'arrival', 'llegada', 'travel'],
  ['der Verkehr', '[fɛɐ̯ˈkeːɐ̯]', 'traffic', 'tráfico', 'travel'],
  ['das Benzin', '[bɛnˈtsiːn]', 'petrol', 'gasolina', 'travel'],
  ['der Führerschein', '[ˈfyːʁɐˌʃaɪn]', 'driving licence', 'licencia de conducir', 'travel'],
  ['der Parkplatz', '[ˈpaʁkˌplats]', 'parking lot', 'estacionamiento', 'travel'],
  ['das Taxi', '[ˈtaksi]', 'taxi', 'taxi', 'travel'],
  ['die Fahrt', '[faːɐ̯t]', 'journey / ride', 'recorrido', 'travel'],

  // ── Work & school (35) ──
  ['die Arbeit', '[ˈaʁbaɪt]', 'work', 'trabajo', 'work'],
  ['der Beruf', '[bəˈʁuːf]', 'profession', 'profesión', 'work'],
  ['das Büro', '[byˈʁoː]', 'office', 'oficina', 'work'],
  ['die Firma', '[ˈfɪʁma]', 'company', 'empresa', 'work'],
  ['der Kollege', '[kɔˈleːɡə]', 'colleague', 'colega', 'work'],
  ['das Geld', '[ɡɛlt]', 'money', 'dinero', 'work'],
  ['der Lohn', '[loːn]', 'wage', 'sueldo', 'work'],
  ['die Schule', '[ˈʃuːlə]', 'school', 'escuela', 'work'],
  ['die Universität', '[univɛʁziˈtɛːt]', 'university', 'universidad', 'work'],
  ['der Lehrer', '[ˈleːʁɐ]', 'teacher', 'maestro', 'work'],
  ['der Schüler', '[ˈʃyːlɐ]', 'pupil', 'alumno', 'work'],
  ['der Student', '[ʃtuˈdɛnt]', 'university student', 'estudiante', 'work'],
  ['die Klasse', '[ˈklasə]', 'class', 'clase', 'work'],
  ['der Unterricht', '[ˈʊntɐˌʁɪçt]', 'lesson / teaching', 'enseñanza', 'work'],
  ['die Aufgabe', '[ˈaʊfˌɡaːbə]', 'task', 'tarea', 'work'],
  ['die Prüfung', '[ˈpʁyːfʊŋ]', 'exam', 'examen', 'work'],
  ['die Note', '[ˈnoːtə]', 'grade', 'calificación', 'work'],
  ['das Buch', '[buːx]', 'book', 'libro', 'work'],
  ['das Heft', '[hɛft]', 'notebook', 'cuaderno', 'work'],
  ['der Stift', '[ʃtɪft]', 'pen', 'pluma', 'work'],
  ['das Papier', '[paˈpiːɐ̯]', 'paper', 'papel', 'work'],
  ['der Computer', '[kɔmˈpjuːtɐ]', 'computer', 'computadora', 'work'],
  ['das Handy', '[ˈhɛndi]', 'mobile phone', 'celular', 'work'],
  ['die E-Mail', '[ˈiːmeːl]', 'email', 'correo electrónico', 'work'],
  ['das Telefon', '[teleˈfoːn]', 'telephone', 'teléfono', 'work'],
  ['die Besprechung', '[bəˈʃpʁɛçʊŋ]', 'meeting', 'reunión', 'work'],
  ['das Projekt', '[pʁoˈjɛkt]', 'project', 'proyecto', 'work'],
  ['die Idee', '[iˈdeː]', 'idea', 'idea', 'work'],
  ['die Frage', '[ˈfʁaːɡə]', 'question', 'pregunta', 'work'],
  ['die Antwort', '[ˈantvɔʁt]', 'answer', 'respuesta', 'work'],
  ['das Wort', '[vɔʁt]', 'word', 'palabra', 'work'],
  ['die Sprache', '[ˈʃpʁaːxə]', 'language', 'idioma', 'work'],
  ['der Text', '[tɛkst]', 'text', 'texto', 'work'],
  ['die Zeitung', '[ˈtsaɪtʊŋ]', 'newspaper', 'periódico', 'work'],
  ['das Studium', '[ˈʃtuːdiʊm]', 'studies', 'estudios', 'work'],

  // ── City & places (30) ──
  ['die Stadt', '[ʃtat]', 'city', 'ciudad', 'city'],
  ['das Dorf', '[dɔʁf]', 'village', 'pueblo', 'city'],
  ['das Land', '[lant]', 'country', 'país', 'city'],
  ['der Platz', '[plats]', 'square', 'plaza', 'city'],
  ['der Markt', '[maʁkt]', 'market', 'mercado', 'city'],
  ['das Geschäft', '[ɡəˈʃɛft]', 'shop / business', 'negocio', 'city'],
  ['der Laden', '[ˈlaːdən]', 'small store', 'tienda', 'city'],
  ['die Bank', '[baŋk]', 'bank', 'banco', 'city'],
  ['die Post', '[pɔst]', 'post office', 'oficina de correos', 'city'],
  ['die Kirche', '[ˈkɪʁçə]', 'church', 'iglesia', 'city'],
  ['das Museum', '[muˈzeːʊm]', 'museum', 'museo', 'city'],
  ['das Kino', '[ˈkiːnoː]', 'cinema', 'cine', 'city'],
  ['das Theater', '[teˈaːtɐ]', 'theatre', 'teatro', 'city'],
  ['der Park', '[paʁk]', 'park', 'parque', 'city'],
  ['die Brücke', '[ˈbʁʏkə]', 'bridge', 'puente', 'city'],
  ['der Turm', '[tʊʁm]', 'tower', 'torre', 'city'],
  ['das Zentrum', '[ˈtsɛntʁʊm]', 'centre', 'centro', 'city'],
  ['die Ecke', '[ˈɛkə]', 'corner', 'esquina', 'city'],
  ['die Polizei', '[poliˈtsaɪ]', 'police', 'policía', 'city'],
  ['die Bibliothek', '[biblioˈteːk]', 'library', 'biblioteca', 'city'],
  ['der Supermarkt', '[ˈzuːpɐˌmaʁkt]', 'supermarket', 'supermercado', 'city'],
  ['die Bäckerei', '[bɛkəˈʁaɪ]', 'bakery', 'panadería', 'city'],
  ['das Café', '[kaˈfeː]', 'café', 'cafetería', 'city'],
  ['der Zoo', '[tsoː]', 'zoo', 'zoológico', 'city'],
  ['das Schwimmbad', '[ˈʃvɪmˌbaːt]', 'swimming pool', 'alberca', 'city'],
  ['die Adresse', '[aˈdʁɛsə]', 'address', 'dirección', 'city'],
  ['die Nummer', '[ˈnʊmɐ]', 'number', 'número', 'city'],
  ['das Gebäude', '[ɡəˈbɔɪdə]', 'building', 'edificio', 'city'],
  ['der Eingang', '[ˈaɪnˌɡaŋ]', 'entrance', 'entrada', 'city'],
  ['der Ausgang', '[ˈaʊsˌɡaŋ]', 'exit', 'salida', 'city'],

  // ── Nature & weather (30) ──
  ['die Natur', '[naˈtuːɐ̯]', 'nature', 'naturaleza', 'nature'],
  ['das Wetter', '[ˈvɛtɐ]', 'weather', 'clima', 'nature'],
  ['die Sonne', '[ˈzɔnə]', 'sun', 'sol', 'nature'],
  ['der Mond', '[moːnt]', 'moon', 'luna', 'nature'],
  ['der Stern', '[ʃtɛʁn]', 'star', 'estrella', 'nature'],
  ['der Himmel', '[ˈhɪməl]', 'sky', 'cielo', 'nature'],
  ['die Wolke', '[ˈvɔlkə]', 'cloud', 'nube', 'nature'],
  ['der Regen', '[ˈʁeːɡən]', 'rain', 'lluvia', 'nature'],
  ['der Schnee', '[ʃneː]', 'snow', 'nieve', 'nature'],
  ['der Wind', '[vɪnt]', 'wind', 'viento', 'nature'],
  ['der Sturm', '[ʃtʊʁm]', 'storm', 'tormenta', 'nature'],
  ['die Hitze', '[ˈhɪtsə]', 'heat', 'calor', 'nature'],
  ['die Kälte', '[ˈkɛltə]', 'cold', 'frío', 'nature'],
  ['das Feuer', '[ˈfɔɪɐ]', 'fire', 'fuego', 'nature'],
  ['die Luft', '[lʊft]', 'air', 'aire', 'nature'],
  ['die Erde', '[ˈeːɐ̯də]', 'earth', 'tierra', 'nature'],
  ['der Baum', '[baʊm]', 'tree', 'árbol', 'nature'],
  ['die Blume', '[ˈbluːmə]', 'flower', 'flor', 'nature'],
  ['das Gras', '[ɡʁaːs]', 'grass', 'pasto', 'nature'],
  ['der Wald', '[valt]', 'forest', 'bosque', 'nature'],
  ['der Berg', '[bɛʁk]', 'mountain', 'montaña', 'nature'],
  ['der See', '[zeː]', 'lake', 'lago', 'nature'],
  ['das Meer', '[meːɐ̯]', 'sea', 'mar', 'nature'],
  ['der Fluss', '[flʊs]', 'river', 'río', 'nature'],
  ['der Strand', '[ʃtʁant]', 'beach', 'playa', 'nature'],
  ['das Tier', '[tiːɐ̯]', 'animal', 'animal', 'nature'],
  ['der Hund', '[hʊnt]', 'dog', 'perro', 'nature'],
  ['die Katze', '[ˈkatsə]', 'cat', 'gato', 'nature'],
  ['der Vogel', '[ˈfoːɡəl]', 'bird', 'pájaro', 'nature'],
  ['das Pferd', '[pfeːɐ̯t]', 'horse', 'caballo', 'nature'],

  // ── Common verbs (70) ──
  ['sein', '[zaɪn]', 'to be', 'ser / estar', 'verb'],
  ['haben', '[ˈhaːbən]', 'to have', 'tener', 'verb'],
  ['werden', '[ˈveːɐ̯dən]', 'to become', 'volverse', 'verb'],
  ['können', '[ˈkœnən]', 'to be able to', 'poder', 'verb'],
  ['müssen', '[ˈmʏsən]', 'to have to', 'tener que', 'verb'],
  ['wollen', '[ˈvɔlən]', 'to want', 'querer', 'verb'],
  ['sollen', '[ˈzɔlən]', 'should / ought to', 'deber', 'verb'],
  ['dürfen', '[ˈdʏʁfən]', 'to be allowed to', 'tener permiso de', 'verb'],
  ['mögen', '[ˈmøːɡən]', 'to like', 'gustar', 'verb'],
  ['machen', '[ˈmaxən]', 'to make / do', 'hacer', 'verb'],
  ['gehen', '[ˈɡeːən]', 'to go', 'ir', 'verb'],
  ['kommen', '[ˈkɔmən]', 'to come', 'venir', 'verb'],
  ['fahren', '[ˈfaːʁən]', 'to drive / travel', 'conducir', 'verb'],
  ['laufen', '[ˈlaʊfən]', 'to run / walk', 'correr', 'verb'],
  ['stehen', '[ˈʃteːən]', 'to stand', 'estar de pie', 'verb'],
  ['sitzen', '[ˈzɪtsən]', 'to sit', 'estar sentado', 'verb'],
  ['liegen', '[ˈliːɡən]', 'to lie / be located', 'estar acostado', 'verb'],
  ['legen', '[ˈleːɡən]', 'to lay down', 'poner', 'verb'],
  ['stellen', '[ˈʃtɛlən]', 'to place upright', 'colocar', 'verb'],
  ['setzen', '[ˈzɛtsən]', 'to set / seat', 'sentar', 'verb'],
  ['bleiben', '[ˈblaɪbən]', 'to stay', 'quedarse', 'verb'],
  ['sehen', '[ˈzeːən]', 'to see', 'ver', 'verb'],
  ['schauen', '[ˈʃaʊən]', 'to look', 'mirar', 'verb'],
  ['hören', '[ˈhøːʁən]', 'to hear', 'oír', 'verb'],
  ['sprechen', '[ˈʃpʁɛçən]', 'to speak', 'hablar', 'verb'],
  ['sagen', '[ˈzaːɡən]', 'to say', 'decir', 'verb'],
  ['reden', '[ˈʁeːdən]', 'to talk', 'conversar', 'verb'],
  ['fragen', '[ˈfʁaːɡən]', 'to ask', 'preguntar', 'verb'],
  ['antworten', '[ˈantvɔʁtən]', 'to answer', 'responder', 'verb'],
  ['lesen', '[ˈleːzən]', 'to read', 'leer', 'verb'],
  ['schreiben', '[ˈʃʁaɪbən]', 'to write', 'escribir', 'verb'],
  ['lernen', '[ˈlɛʁnən]', 'to learn', 'aprender', 'verb'],
  ['studieren', '[ʃtuˈdiːʁən]', 'to study', 'estudiar', 'verb'],
  ['arbeiten', '[ˈaʁbaɪtən]', 'to work', 'trabajar', 'verb'],
  ['spielen', '[ˈʃpiːlən]', 'to play', 'jugar', 'verb'],
  ['essen', '[ˈɛsən]', 'to eat', 'comer', 'verb'],
  ['trinken', '[ˈtʁɪŋkən]', 'to drink', 'beber', 'verb'],
  ['kochen', '[ˈkɔxən]', 'to cook', 'cocinar', 'verb'],
  ['kaufen', '[ˈkaʊfən]', 'to buy', 'comprar', 'verb'],
  ['verkaufen', '[fɛɐ̯ˈkaʊfən]', 'to sell', 'vender', 'verb'],
  ['bezahlen', '[bəˈtsaːlən]', 'to pay', 'pagar', 'verb'],
  ['kosten', '[ˈkɔstən]', 'to cost', 'costar', 'verb'],
  ['geben', '[ˈɡeːbən]', 'to give', 'dar', 'verb'],
  ['nehmen', '[ˈneːmən]', 'to take', 'tomar', 'verb'],
  ['bringen', '[ˈbʁɪŋən]', 'to bring', 'traer', 'verb'],
  ['holen', '[ˈhoːlən]', 'to fetch', 'ir por', 'verb'],
  ['finden', '[ˈfɪndən]', 'to find', 'encontrar', 'verb'],
  ['suchen', '[ˈzuːxən]', 'to look for', 'buscar', 'verb'],
  ['brauchen', '[ˈbʁaʊxən]', 'to need', 'necesitar', 'verb'],
  ['helfen', '[ˈhɛlfən]', 'to help', 'ayudar', 'verb'],
  ['danken', '[ˈdaŋkən]', 'to thank', 'agradecer', 'verb'],
  ['warten', '[ˈvaʁtən]', 'to wait', 'esperar', 'verb'],
  ['hoffen', '[ˈhɔfən]', 'to hope', 'tener esperanza', 'verb'],
  ['denken', '[ˈdɛŋkən]', 'to think', 'pensar', 'verb'],
  ['wissen', '[ˈvɪsən]', 'to know (a fact)', 'saber', 'verb'],
  ['kennen', '[ˈkɛnən]', 'to know (be familiar with)', 'conocer', 'verb'],
  ['verstehen', '[fɛɐ̯ˈʃteːən]', 'to understand', 'entender', 'verb'],
  ['glauben', '[ˈɡlaʊbən]', 'to believe', 'creer', 'verb'],
  ['lieben', '[ˈliːbən]', 'to love', 'amar', 'verb'],
  ['leben', '[ˈleːbən]', 'to live / be alive', 'vivir', 'verb'],
  ['wohnen', '[ˈvoːnən]', 'to reside', 'residir', 'verb'],
  ['schlafen', '[ˈʃlaːfən]', 'to sleep', 'dormir', 'verb'],
  ['aufstehen', '[ˈaʊfˌʃteːən]', 'to get up', 'levantarse', 'verb'],
  ['anfangen', '[ˈanˌfaŋən]', 'to begin', 'empezar', 'verb'],
  ['aufhören', '[ˈaʊfˌhøːʁən]', 'to stop', 'parar', 'verb'],
  ['öffnen', '[ˈœfnən]', 'to open', 'abrir', 'verb'],
  ['schließen', '[ˈʃliːsən]', 'to close', 'cerrar', 'verb'],
  ['treffen', '[ˈtʁɛfən]', 'to meet', 'encontrarse con', 'verb'],
  ['besuchen', '[bəˈzuːxən]', 'to visit', 'visitar', 'verb'],
  ['vergessen', '[fɛɐ̯ˈɡɛsən]', 'to forget', 'olvidar', 'verb'],

  // ── Common adjectives (50) ──
  ['gut', '[ɡuːt]', 'good', 'bueno', 'adj'],
  ['schlecht', '[ʃlɛçt]', 'bad', 'malo', 'adj'],
  ['groß', '[ɡʁoːs]', 'big', 'grande', 'adj'],
  ['klein', '[klaɪn]', 'small', 'pequeño', 'adj'],
  ['neu', '[nɔɪ]', 'new', 'nuevo', 'adj'],
  ['alt', '[alt]', 'old', 'viejo', 'adj'],
  ['jung', '[jʊŋ]', 'young', 'joven', 'adj'],
  ['lang', '[laŋ]', 'long', 'largo', 'adj'],
  ['kurz', '[kʊʁts]', 'short', 'corto', 'adj'],
  ['hoch', '[hoːx]', 'high / tall', 'alto', 'adj'],
  ['niedrig', '[ˈniːdʁɪç]', 'low', 'bajo', 'adj'],
  ['schnell', '[ʃnɛl]', 'fast', 'rápido', 'adj'],
  ['langsam', '[ˈlaŋzaːm]', 'slow', 'lento', 'adj'],
  ['warm', '[vaʁm]', 'warm', 'cálido', 'adj'],
  ['kalt', '[kalt]', 'cold', 'frío', 'adj'],
  ['heiß', '[haɪs]', 'hot', 'caliente', 'adj'],
  ['teuer', '[ˈtɔɪɐ]', 'expensive', 'caro', 'adj'],
  ['billig', '[ˈbɪlɪç]', 'cheap', 'barato', 'adj'],
  ['schön', '[ʃøːn]', 'beautiful', 'hermoso', 'adj'],
  ['hässlich', '[ˈhɛslɪç]', 'ugly', 'feo', 'adj'],
  ['einfach', '[ˈaɪnfax]', 'easy / simple', 'fácil', 'adj'],
  ['schwer', '[ʃveːɐ̯]', 'difficult / heavy', 'difícil', 'adj'],
  ['leicht', '[laɪçt]', 'light (in weight)', 'ligero', 'adj'],
  ['stark', '[ʃtaʁk]', 'strong', 'fuerte', 'adj'],
  ['schwach', '[ʃvax]', 'weak', 'débil', 'adj'],
  ['richtig', '[ˈʁɪçtɪç]', 'correct', 'correcto', 'adj'],
  ['falsch', '[falʃ]', 'wrong', 'incorrecto', 'adj'],
  ['wichtig', '[ˈvɪçtɪç]', 'important', 'importante', 'adj'],
  ['interessant', '[ɪntəʁɛˈsant]', 'interesting', 'interesante', 'adj'],
  ['langweilig', '[ˈlaŋvaɪlɪç]', 'boring', 'aburrido', 'adj'],
  ['glücklich', '[ˈɡlʏklɪç]', 'happy', 'feliz', 'adj'],
  ['traurig', '[ˈtʁaʊʁɪç]', 'sad', 'triste', 'adj'],
  ['müde', '[ˈmyːdə]', 'tired', 'cansado', 'adj'],
  ['krank', '[kʁaŋk]', 'sick', 'enfermo', 'adj'],
  ['gesund', '[ɡəˈzʊnt]', 'healthy', 'sano', 'adj'],
  ['hungrig', '[ˈhʊŋʁɪç]', 'hungry', 'hambriento', 'adj'],
  ['durstig', '[ˈdʊʁstɪç]', 'thirsty', 'sediento', 'adj'],
  ['freundlich', '[ˈfʁɔɪntlɪç]', 'friendly', 'amable', 'adj'],
  ['nett', '[nɛt]', 'nice', 'simpático', 'adj'],
  ['böse', '[ˈbøːzə]', 'angry / evil', 'enojado', 'adj'],
  ['ruhig', '[ˈʁuːɪç]', 'calm', 'tranquilo', 'adj'],
  ['laut', '[laʊt]', 'loud', 'ruidoso', 'adj'],
  ['leise', '[ˈlaɪzə]', 'quiet / soft', 'silencioso', 'adj'],
  ['sauber', '[ˈzaʊbɐ]', 'clean', 'limpio', 'adj'],
  ['schmutzig', '[ˈʃmʊtsɪç]', 'dirty', 'sucio', 'adj'],
  ['voll', '[fɔl]', 'full', 'lleno', 'adj'],
  ['leer', '[leːɐ̯]', 'empty', 'vacío', 'adj'],
  ['offen', '[ˈɔfən]', 'open', 'abierto', 'adj'],
  ['geschlossen', '[ɡəˈʃlɔsən]', 'closed', 'cerrado', 'adj'],
  ['frei', '[fʁaɪ]', 'free / available', 'libre', 'adj'],

  // ── Function words (25) ──
  ['ich', '[ɪç]', 'I', 'yo', 'fn'],
  ['du', '[duː]', 'you (informal)', 'tú', 'fn'],
  ['er', '[eːɐ̯]', 'he', 'él', 'fn'],
  ['sie', '[ziː]', 'she / they', 'ella / ellos', 'fn'],
  ['wir', '[viːɐ̯]', 'we', 'nosotros', 'fn'],
  ['ihr', '[iːɐ̯]', 'you (plural)', 'ustedes', 'fn'],
  ['und', '[ʊnt]', 'and', 'y', 'fn'],
  ['oder', '[ˈoːdɐ]', 'or', 'o', 'fn'],
  ['aber', '[ˈaːbɐ]', 'but', 'pero', 'fn'],
  ['weil', '[vaɪl]', 'because', 'porque', 'fn'],
  ['wenn', '[vɛn]', 'if / when', 'si', 'fn'],
  ['dass', '[das]', 'that', 'que', 'fn'],
  ['nicht', '[nɪçt]', 'not', 'no', 'fn'],
  ['kein', '[kaɪn]', 'no / none', 'ningún', 'fn'],
  ['auch', '[aʊx]', 'also', 'también', 'fn'],
  ['nur', '[nuːɐ̯]', 'only', 'sólo', 'fn'],
  ['sehr', '[zeːɐ̯]', 'very', 'muy', 'fn'],
  ['noch', '[nɔx]', 'still / yet', 'todavía', 'fn'],
  ['schon', '[ʃoːn]', 'already', 'ya', 'fn'],
  ['hier', '[hiːɐ̯]', 'here', 'aquí', 'fn'],
  ['dort', '[dɔʁt]', 'there', 'allí', 'fn'],
  ['wo', '[voː]', 'where', 'dónde', 'fn'],
  ['was', '[vas]', 'what', 'qué', 'fn'],
  ['wer', '[veːɐ̯]', 'who', 'quién', 'fn'],
  ['wie', '[viː]', 'how', 'cómo', 'fn'],
];

// Expand the table into cards. Distractors come from the same category so the
// quiz tests the word rather than the topic; the walk is deterministic so the
// deck is identical on every load.
function buildDeck(lang) {
  const byCat = new Map();
  W.forEach((row, i) => {
    const cat = row[4];
    if (!byCat.has(cat)) byCat.set(cat, []);
    byCat.get(cat).push(i);
  });

  const translate = i => (lang === 'es' ? W[i][3] : W[i][2]);

  return W.map(([word, ipa, en, es, cat], i) => {
    const correct = lang === 'es' ? es : en;
    const group = byCat.get(cat);
    const pos = group.indexOf(i);
    const options = [correct];

    for (let step = 1; options.length < 4 && step < group.length; step++) {
      const cand = translate(group[(pos + step) % group.length]);
      if (!options.includes(cand)) options.push(cand);
    }
    // Safety net if a category ever shrinks below four distinct translations.
    for (let j = 0; options.length < 4 && j < W.length; j++) {
      const cand = translate(j);
      if (!options.includes(cand)) options.push(cand);
    }

    return {
      id: i + 1,
      word,
      ipa,
      question: lang === 'es' ? `¿Qué significa '${word}'?` : `What does '${word}' mean?`,
      options,
      correctIndex: 0,
      reference: CATEGORY_LABEL[cat][lang === 'es' ? 'es' : 'en'],
    };
  });
}

export const TOP_500_WORDS_QUIZ = {
  en: buildDeck('en'),
  es: buildDeck('es'),
};
